- source/lib/accounts.js
- source/lib/allowances.js
The optionsync does not really help here because we do not have any defaults. Thus it is simpler to just directly use the browser storage API
> Remove optionsync from accounts and allowances storage

- src/app/components/Home/Transactions.jsx
- src/app/components/Home/index.jsx
- src/common/utils/helpers.js
- src/extension/background-script/connectors/lnd.js
Fetching `/payments` instead of `/transactions`
> Fetch correct transactions from node

- README.md
- src/app/components/Options/Options.jsx
- src/app/components/Unlock/index.jsx
- src/app/components/Welcome/Welcome.jsx
- src/common/lib/settings.js
- src/extension/background-script/index.js
Added this changes to make it a bit easier for new developers to run it. 
It allows to add the development account with one click and opens the welcome page if no account is available.
> Simplify initial setup

- src/manifest.json
> Cleanup `manifest.json`

- src/app/screens/Onboard/SetPassword/index.jsx
The form wasn't working well anymore due to event.preventDefault being called too late.
> fix: preventdefault needs to be called before await

- src/app/router/Popup/Popup.jsx
- src/extension/background-script/actions/setup/index.js
- src/extension/background-script/actions/setup/reset.js
- src/extension/background-script/actions/setup/status.js
- src/extension/background-script/router.js
- src/extension/background-script/state.js
- src/extension/inpage-script/index.js
This tries to find a lightning invoice from a bitcoin link. Basically any link that contains lightning=lnbc
> Bitcoin links

- webpack.config.js
Prod builds seem too large currently.
> Performance: remove sourcemaps in prod and minimize js

- src/app/components/Navbar/Navbar.tsx
- src/app/router/Options/Options.jsx
- src/app/screens/Enable/index.jsx
- src/app/screens/Home/index.jsx
- src/extension/background-script/actions/accounts/index.js
- src/extension/background-script/actions/accounts/info.js
- Do not show options icon in navbar if no options handler is provided
- Load account info and details into the navbar
- Remember the enable option by default
> Load real wallet data for navbar

- src/extension/background-script/actions/allowances/add.js
- src/extension/background-script/actions/allowances/enable.js
- src/extension/background-script/actions/allowances/list.js
The allowance that was last used is at the top
> Sort allowances by last payment at

- src/app/screens/Home/index.jsx
- src/extension/background-script/actions/allowances/get.js
When you visit for e.g. https://lightning-roulette.com/ and there is an allowance already set, the extension will show the publisher/payments when opening the extension.
If not, it will show the default view.
> Contextual home

- src/app/components/Container.tsx
- src/app/components/TransactionsTable/index.tsx
- src/app/router/Options/Options.jsx
- src/app/screens/Publisher.tsx
- src/app/styles/index.css
- static/views/lsat.html
- static/views/options.html
- static/views/popup.html
- static/views/prompt.html
- static/views/welcome.html
The Transactionstable can now be used in very small sizes.
I created a container component to use within option screens (with a new introduced max-width).
> Responsive Transactionstable & Container component

- package.json
- src/app/router/Prompt/Prompt.jsx
- src/app/screens/ConfirmPayment/index.jsx
- src/extension/background-script/actions/ln/sendPayment.js
- yarn.lock
https://github.com/bumi/lightning-browser-extension/issues/142
> Drop node-lightning/invoice package

- src/extension/background-script/actions/lnurl/index.ts
- src/extension/background-script/events/notifications.js
> Add parsed URL to lnurlDetails object

- src/common/lib/lnurl.ts
- src/extension/background-script/actions/lnurl/index.ts
Improved code readability / functional programming.
> refactor: lnurl getDetails method

- README.md
Just wanted to avoid the connection to Jeff Bezos. Unless that was intentional, but I'll assume it was not.
But seriously, thanks for dropping the note in the README, and really excited to see all the progress here. 100% agree with the "why not joule" section and really glad to see a more agnostic and lightweight solution in the works. I'll be hanging out in the Slack channel, feel free to ping me if there's anything you need from me!
> Fix typo in thanks section

- .github/workflows/build.yml
- src/app/screens/LNURLAuth.tsx
- src/app/screens/Onboard/TestConnection/index.jsx
- src/extension/background-script/actions/ln/index.js
- src/extension/background-script/actions/ln/makeInvoice.js
- src/extension/background-script/connectors/lnd.js
- src/extension/background-script/connectors/lndhub.js
- src/extension/background-script/router.js
- webpack.config.js
This gives users with a zero balance a small faucet to quickly get started and test the extension
> Add LN faucet

- src/common/lib/lnurl.ts
This tries to find LNURLs from a string.
An LNURL can either be a bech32 encoded string (LNURL...) or one with a LNURL scheme (lnurlp://) or a lightning address
> Better LNURL discovery

- src/app/components/Menu/Menu.stories.tsx
- src/app/components/Menu/MenuDivider.tsx
- src/app/components/Menu/MenuItem.tsx
- src/app/components/Menu/MenuList.tsx
- src/app/components/Menu/MenuSubheader.tsx
- src/app/components/Menu/index.tsx
- src/app/components/Shared/badge.jsx
- src/app/components/UserMenu/index.tsx
- src/app/router/Options/Options.jsx
- src/app/router/Popup/styles.scss
- src/app/screens/Home/index.jsx
- src/app/screens/Onboard/ConnectLnd/index.jsx
- src/app/screens/Options/ChooseConnector/index.jsx
- src/app/screens/Options/TestConnection/index.jsx
- src/extension/background-script/actions/accounts/add.js
- src/extension/background-script/actions/accounts/all.js
- src/extension/background-script/actions/accounts/index.js
- src/extension/background-script/router.js
- src/stories/Badge.stories.js
- static/views/options.html
- tailwind.config.js
This extends the menu according to the new figma designs.
> feat: subheader, divider & badges

- src/app/screens/Onboard/ChooseConnector/index.tsx
- src/app/screens/Onboard/ConnectLnbits/index.jsx
- src/app/screens/Options/ChooseConnector/index.jsx
- src/extension/background-script/connectors/lnbits.js
this allows the user to use an LNbits account.
Connection is done with the LNbits URL and the admin key
> Add LNbits connector

- src/app/components/TransactionsTable/index.tsx
If there are any style changes you like, ill be happy to add
Resolves: #214
> Add preimage and disclosure to transaction table

- src/extension/content-script/batteries/YouTubeVideo.js
- src/extension/content-script/batteries/index.js
- src/extension/inpage-script/index.js
this can either be a lnurlp: or lightning: text or a lightning address with a ⚡️: prefix
> YouTube battery: load LNURL from a YouTube video description

- .github/workflows/build.yml
- src/app/components/PaymentSummary.tsx
- src/app/screens/Home/index.jsx
- src/app/screens/LNURLPay.tsx
- src/extension/background-script/connectors/lnbits.js
- src/manifest.json
This updates the name and description of the extension and some wording. 
When we merge this you will have to reconfigure your node and the data will be lost.
> Using Alby as the official name of the extension

- src/app/components/AllowanceMenu/AllowanceMenu.stories.tsx
- src/app/components/AllowanceMenu/index.tsx
- src/app/components/Menu/MenuList.tsx
- src/app/screens/Home/index.jsx
- src/app/screens/Publisher.tsx
> feat: edit or delete allowance from popup

- create-packages.sh
- package.json
- src/manifest.json
To publish the extension in the add-on stores we have to have deterministic builds.
This adds a script to create deterministic zip files
> Package script

- src/app/components/AllowanceMenu/index.tsx
- src/app/components/PaymentSummary.tsx
- src/app/components/TransactionsTable/index.tsx
- src/app/router/Options/Options.jsx
- src/app/router/Popup/Popup.jsx
- src/app/screens/ConfirmPayment/index.jsx
- src/app/screens/Home/index.jsx
- src/app/screens/LNURLPay.tsx
- src/app/screens/Onboard/ConnectLnbits/index.tsx
- src/app/screens/Onboard/ConnectLnd/index.tsx
- src/app/screens/Onboard/ConnectLndHub/index.tsx
- src/app/screens/Onboard/Intro/index.jsx
- src/app/screens/Onboard/NewWallet/index.tsx
- src/app/screens/Onboard/SetPassword/index.jsx
- src/app/screens/Onboard/TestConnection/index.jsx
- src/app/screens/Options/TestConnection/index.jsx
- src/app/screens/Receive.tsx
- src/extension/background-script/events/notifications.js
Update all instances of 'sats', 'satoshi' etc. to a unified 'sat' wording as decided in #308. I think I have found them all but I may have missed some. If so just let me know.
> Sat word update

- src/app/components/PaymentSummary.tsx
- src/common/lib/utils.ts
- static/views/prompt.html
> [Fix] Scrollbars on prompt window

- src/app/router/Options/Options.jsx
- src/app/router/Popup/Popup.jsx
> feat: reset account to initial state before loading

- static/views/popup.html
> feat: disallow horizontal scrollbar in popup

- src/app/screens/Onboard/ConnectLnbits/index.tsx
- src/extension/background-script/actions/ln/makeInvoice.js
- src/extension/background-script/connectors/lnbits.js
> Fix invoice creation with LNbits

- src/app/components/PaymentSummary.tsx
- src/extension/background-script/actions/ln/makeInvoice.js
https://webln.dev/#/api/make-invoice describes using defaultMemo
> Support default memo

- src/types.ts
> fix: successaction potentially undefined

- src/app/components/AllowanceMenu/index.tsx
As requested by @MoritzKa in #441
> Change publisher to website

- src/extension/background-script/connectors/base.ts
- src/extension/background-script/connectors/connector.example
- src/extension/background-script/connectors/connector.interface.ts
- src/extension/background-script/connectors/index.ts
- src/extension/background-script/connectors/lnbits.ts
- src/extension/background-script/connectors/lnd.ts
- src/extension/background-script/connectors/lndhub.ts
- src/extension/background-script/state.ts
> Improve connector types with individual configs

- src/extension/background-script/actions/accounts/select.js
- src/extension/background-script/state.ts
(not sure if this causes a caching problem in some cases?)
> Make sure to load cached connector class and not reinitialize

- src/app/components/UserMenu/index.tsx
I added a feedback button to the popup menu and to the navbar. I also created a feedback component which currently just says 'Thank you for providing feedback to Alby!' but can be updated in the future to have an embedded feedback form. This was my first time using React Router and I just went off the current code as an example, I have been meaning to take a course on it so if I did anything wrong there just let me know. Both buttons open a new tab to: https://feedback.getalby.com
Screenshots:
Check it out @MoritzKa !
> Feedback button

- src/app/components/TransactionsTable/index.tsx
- src/app/screens/Publisher.tsx
- src/types.ts
Requested in issue #446, I am not sure if this is exactly what you wanted @bumi so please review and let me know. Thanks!
> Add payment location link in tx table

- src/extension/content-script/batteries/Twitter.ts
- tsconfig.json
So far we had only looked for the first occurance of the ⚡️emoji. This means we did not find any lightning address when there have been multiple emojis before the ln address.
This change iterates through all or the elements and tries to find an ln address.
> Check all ⚡️emojis in the twitter bio

- package.json
- src/app/context/AuthContext.tsx
- src/app/router/Options/Options.jsx
- src/app/router/Popup/Popup.jsx
- src/app/screens/Receive.tsx
- src/common/utils/helpers.ts
- src/extension/background-script/actions/ln/checkPayment.ts
- src/extension/background-script/actions/ln/index.js
- src/extension/background-script/connectors/connector.example
- src/extension/background-script/connectors/connector.interface.ts
- src/extension/background-script/connectors/lnbits.ts
- src/extension/background-script/connectors/lnd.ts
- src/extension/background-script/connectors/lndhub.ts
- src/extension/background-script/router.js
- yarn.lock
> feat: check if invoice is paid

- src/app/screens/Home/index.jsx
Not on any other tabs like for example internal settings pages
> Trigger call to extract lightning data only from http sites

- src/app/components/TransactionsTable/index.tsx
Hey sorry I just noticed one small change to make to dark mode after the main PR was merged.
Thanks!
> Minor dark mode update

- src/extension/background-script/connectors/galoy.ts
Can be merged using the **`Rebase & Merge`** feature on here.
This PR targets the #434 branch. I did some testing with the new error additions and all looks well so far. I made one small change here for the uuid format we use now for user ids. It looks visually better if we set the alias to the uuid partial just before the first `-` character.
> Add alias change to #434 PR

- src/app/screens/Onboard/TestConnection/index.jsx
- src/app/screens/Options/TestConnection/index.jsx
Discovered this page needs dark mode styling - had not seen it before.
> Add dark mode to test connection page

- src/app/components/UserMenu/index.tsx
> One more dark mode update

- src/manifest.json
Change extension title and description
> Manifest description

- src/app/components/TransactionsTable/index.tsx
Another minor dark mode update that I found.
> Update tx caret icon hover effect for dark mode

- src/extension/content-script/batteries/YouTubeVideo.ts
I think there was some different/hidden character
> Fix Regex, how do emojis work?

- src/app/screens/LNURLAuth.tsx
Found some text that needs an update for dark mode. 😎
> Update for dark mode

- src/extension/content-script/batteries/YouTubeChannel.ts
- src/extension/content-script/batteries/index.ts
This loads the lightning data from the channel's about text
> Enable tipping on YouTube channels

- src/app/screens/ConfirmPayment/index.jsx
- src/app/screens/Send.tsx
- src/common/lib/lnurl.ts
> feat: handle invalid invoices

- src/app/screens/ConfirmPayment/index.jsx
> feat: show success message after payment in popup

- src/app/screens/Onboard/ConnectLnd/index.tsx
- src/app/screens/Onboard/ConnectLndHub/index.tsx
- src/manifest.json
- src/manifest.json.development.sample
> refactor: optionally ask for native messaging permission

- src/extension/background-script/connectors/lnd.ts
reported in: https://github.com/getAlby/lightning-browser-extension/issues/470
> Support for lnd v0.14 new error format

- src/app/screens/LNURLPay.tsx
sometimes the LNURL details are loaded too slow
> Add a loading spinner to the LNURL pay screen

- src/app/router/Popup/Popup.jsx
Only scroll the content, leave the menu fixed.
> feat: fixed header

- src/app/components/AccountMenu/index.tsx
- src/app/components/Card/index.tsx
- src/app/context/AuthContext.tsx
- src/app/screens/Onboard/TestConnection/index.jsx
- src/app/screens/Options/TestConnection/index.tsx
- src/common/lib/api.ts
- src/extension/background-script/state.ts
- src/types.ts
> Show new account immediately in account list

- README.md
1. fixed broken link
2. checked all other links - other links working fine
> fix: fix broken link in README

- src/app/components/AccountMenu/index.tsx
- src/app/router/Options/Options.jsx
- src/app/screens/Accounts.tsx
- src/common/lib/api.ts
- src/common/lib/cache.ts
- src/extension/background-script/actions/accounts/delete.ts
- src/extension/background-script/actions/accounts/index.js
- src/extension/background-script/router.js
Adds an account page to the options and allows you to delete accounts.
> feat: delete accounts

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- SECURITY.md
Fixes: https://github.com/getAlby/lightning-browser-extension/issues/610
template to report a bug
template to request a feature
blank issue template
discuss on slack  template
security policies
> feat: use templates while creating features and issues

- src/app/screens/LNURLPay.tsx
- src/app/screens/MakeInvoice.tsx
- src/app/screens/Onboard/NewWallet/index.tsx
- src/app/screens/Receive.tsx
Currently labels aren't clickable in those screens and styles are inconsistent.
This makes also the rendering more clear which became too abstract within methods.
> refactor: LNURLPay & MakeInvoice should use the new accessible TextField

- src/app/screens/Accounts.tsx
- src/app/screens/Onboard/ConnectLnd/index.tsx
- src/declarations.d.ts
- src/extension/background-script/actions/accounts/add.ts
- src/extension/background-script/actions/accounts/delete.ts
- src/extension/background-script/state.ts
- src/types.ts
- switch add.js to TS
- add types
If possible would like to add a test for this when #627 is merged
> fix(addAccount): use uuid ad account-id #635

- src/app/screens/Accounts.tsx
Reported in issue #655 I have updated the new account screen to work with dark mode.
> New account screen dark mode updates

- src/app/components/PublishersTable/index.tsx
- src/app/screens/Receive.tsx
> Micro-improving the UX

- src/app/components/CompanionDownloadInfo.tsx
I found a dark mode fix in the companion app text. It was black which did not show up well in dark mode so I changed it to white.
Tested and works.
> fix: dark mode text for companion app

- src/app/components/QrcodeScanner/index.tsx
- src/app/screens/Onboard/ChooseConnector/index.tsx
- src/app/screens/Onboard/ConnectLnd/index.tsx
* show the option the create a new wallet as first option
* smaller boxes for macaroon drop area and QR code scanner
> chore: minor connect wallets UI updates

- src/app/screens/Accounts/index.tsx
- adjust html to be more semantic
- move edit to top of menu instead of delete
#647
> refactor(accounts): use consistent function-params #647

- README.md
- src/app/components/PaymentSummary.tsx
- src/app/router/Prompt/Prompt.tsx
- src/app/screens/LNURLWithdraw.tsx
- src/app/screens/MakeInvoice.tsx
- src/app/screens/Onboard/TestConnection/index.tsx
- src/app/screens/Receive.tsx
- src/common/lib/api.ts
- src/extension/background-script/actions/lnurl/index.ts
- src/extension/background-script/connectors/connector.interface.ts
- src/extension/background-script/connectors/eclair.ts
- src/extension/background-script/connectors/lndhub.ts
- src/types.ts
Tested with Kollider: https://pro.kollider.xyz/ & https://stacker.news/
> feat: add lnurl-withdraw support

- src/app/screens/Onboard/TestConnection/index.tsx
Made the free sats modal have dark mode.
Tested on latest master branch and works as expected.
> Free sats modal dark mode update

- src/extension/background-script/index.js
- src/extension/content-script/batteries/Medium.ts
- src/extension/content-script/batteries/index.ts
Fixes #663 
This PR adds tipping support for medium.com. 
There are 3 places which are currently supported by this battery:
Since the short bio is limited to 160 characters only Lightning Addresses are supported for now.
> Feature: Tipping support for medium.com

- .gitignore
- .vscode/extensions.json
- Dev improvement
vscode users will get recommendations for extensions which help to work with this codebase  
Copied from https://github.com/cstenglein/raspiblitz-web/blob/master/.vscode/extensions.json
> chore: add vscode extension recommendations

- src/app/components/AllowanceMenu/index.tsx
- src/app/components/Menu/Menu.stories.tsx
- src/app/components/Menu/MenuItemButton.tsx
- src/app/screens/Accounts/index.tsx
Fixes #733
- Styling Change (non-breaking change which adds functionality)
Added Danger prop for Menu's Item Button and used it whenever Delete is to be highlighted
> Task highlight delete

- src/app/components/form/Input/index.tsx
Just added a small animation that makes putting focus on an input slightly "slicker" / a bit more playful.
> feat: input focus animation

- src/app/context/AuthContext.tsx
- src/app/router/Options/Options.tsx
- src/app/router/Popup/Popup.tsx
- src/common/lib/api.ts
- src/extension/background-script/actions/accounts/info.js
- src/extension/background-script/state.ts
Fixes #732 
Until now we only showed the node alias in the NavBar. This change also show the name there.
We might want to refactor the NavBar component sometime and make that one load the account details from the AuthContext?
> Show account name and node alias in navbar

- src/app/components/form/Select/index.tsx
- Style update
Updated the new language dropdown selector element to work with dark mode.
Ran code locally and checked for dynamic style updates on dark/light theme switch in browser.
> style: update language dropdown for dark mode

- src/app/screens/LNURLPay.tsx
- src/types.ts
Fixes #761 
Error handling for fetching the invoice via lnurl-pay.
> feat(lnurl-pay): handle fetch invoice errors

- src/extension/content-script/batteries/GitHub.ts
Followup from [here](https://github.com/getAlby/lightning-browser-extension/pull/767#pullrequestreview-938252982).
Fixes some issues with the GitHub battery.
> fix: more specific selectors for github battery

- src/app/screens/Send.tsx
Fixes #ISSUE-NUMBER
support BIP21 URI with BOLT 11 invoice QRCode
Not been fully as I've been having problems scanning QR codes on my laptop.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> feat(send): support BIP21 URI with BOLT 11 invoice QRCode

- package.json
You can set multiple environment variables at a time with cross-env.
> chore: cross-env can handle multiple envs at once

- src/app/components/AccountMenu/AccountMenu.stories.tsx
- src/app/components/Navbar/Navbar.stories.tsx
Fixes #784
Fixed AccountMenu & Navbar stories.
> fix: broken storybook stories

- src/app/screens/Publishers/index.tsx
Fixes heading color on publishers page
> fix: darkmode on alby publishers page

- src/app/screens/Publishers/websites.json
related to this PR: https://github.com/getAlby/lightning-browser-extension/pull/490
- Documentation update
added 2 new entries
not yet. will check after Nightly Release has been built.
> Update websites.json with geyser and bolt.fun

- .github/workflows/build.yml
- src/app/screens/Onboard/TestConnection/index.tsx
- src/app/screens/Options/TestConnection/index.tsx
- webpack.config.js
Some funny people tried to abuse it. And we'll only give some sats to Alby signups now.
- non-breaking change which removes functionality
For accounts with 0 sats balance and when the faucet was enabled we now no longer give the faucet option.
> Remove the sats faucet 

- README.md
Made it cleaner, improved the language. Edited for typos. No change in instructions or flow.
Fixes #ISSUE-NUMBER
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation update
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> Updated for grammar and typos

- src/app/screens/Publishers/websites.json
- Documentation update
Update sats4likes link
> chore: update old sats4likes link

- src/app/screens/connectors/ConnectMyNode/index.tsx
- src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
Fixes #847 
I added the myNode and Raspiblitz connector videos to the onboarding screens.
Checked both connectors and that the video plays properly.
> feat: add myNode and raspiblitz videos to connectors

- src/app/components/BudgetControl/index.tsx
- src/app/components/PaymentSummary.tsx
PaymentSummary (in ConfirmPayment) styling should match new styling according to LnurlPay screen.
- Remove the card styling.
> feat: update payment summary styling

- jest.setup.ts
- package.json
- yarn.lock
Upgrade from 0.8.0 to 0.9.0. This breaks our tests initially, so a small change to the setup was needed.
> chore: update webextension-polyfill

- src/app/screens/Settings.tsx
> feat: reorganize settings page

- README.md
Adding storyook setup to the readme
> docs: add storybook info

- babel.config.json
Update browser targets to be more flexible
> chore: update browser targets

- README.md
> docs: add test-account info

- babel.config.json
Not sure, but for me the extension wasn't working correctly anymore.  
Will have a closer look and adjust this later on.
> Revert "chore: update browser targets"

- .github/workflows/linting.yml
- .github/workflows/typecheck.yml
- .github/workflows/unit-tests.yml
Fixes #912
- CI improvement
Split workflow into 3 seperate ones
\-
\-
> chore(ci): split up codequality workflow #912

- src/common/lib/utils.ts
- src/extension/background-script/actions/ln/keysend.ts
- src/extension/background-script/actions/ln/sendPayment.ts
- src/extension/background-script/events/persistPayments.js
- src/types.ts
Before we did not store the keysend payments properly
Currently keysend payments did not have all the required information and have not been properly persisted and shown in the transaction list.
> fix: publish correct payment notification for keysend payments

- tests/e2e/createWallets.spec.ts
we have the server regtest setup now running and everything should be green
> test: activate full create wallet e2e test

- README.md
> docs: update community-call day

- tests/e2e/createWallets.spec.ts
> e2e Tests for LNBits and BlueWallet

- babel.config.json
- yarn.lock
https://browserslist.dev/?q=bGFzdCA1IENocm9tZSB2ZXJzaW9ucywgbGFzdCA1IEVkZ2UgdmVyc2lvbnMsIGxhc3QgNSBPcGVyYSB2ZXJzaW9ucywgbGFzdCA1IEZpcmVmb3ggdmVyc2lvbnM%3D
Friend noticed this should be further reduced
> chore: reduce browser targets

- src/app/components/Container.tsx
- src/app/screens/ConfirmKeysend/index.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/ConfirmSignMessage/index.tsx
- src/app/screens/Keysend/index.tsx
- src/app/screens/LNURLPay.tsx
- src/app/screens/LNURLWithdraw.tsx
- src/app/screens/MakeInvoice.tsx
- src/app/screens/Receive.tsx
- src/app/screens/Send.tsx
- Fix: on fullscreen, webln.makeInvoice() presents a 100% wide screen where forms are stretched.
- Adjust Container to be used with max-w-screen-sm
> fix: prevent horizontal stretching by using a container

- src/app/screens/Publishers/websites.json
Removed LNGames from Websites screen, because the url and Twitter are not active anymore.
no issue available
not yet.
> Update websites.json, Removed LNGames from Websites screen

- README.md
Draft to improve the contribution section. Happy for any feedback!
> docs: improve contribution section

- src/app/components/Button/index.tsx
- src/app/components/IconButton/index.tsx
- src/app/components/PublishersTable/index.tsx
- src/app/components/TransactionsTable/index.tsx
- src/app/components/form/Input/index.tsx
- src/app/screens/Home/index.tsx
- src/app/screens/Settings.tsx
- Buttons with shadows and borders look dated, replaced by just shadow. 
- Fixed some border colors in dark mode 
- Bolder header in Home 
- Removed shadows from input fields.
Before:
After:
> feat: subtle ui improvements

- src/app/components/AccountMenu/index.test.tsx
- src/app/screens/ConfirmPayment/index.test.tsx
Replaced `fireEvent` with `userEvent` as requested.
Closes #940
Used `act()` as it was suggested in the errors to be used whenever we are changing state of react component while testing.
- `test`: Update tests (adding missing tests, refactoring tests; no production code change)
Ran all tests with no errors
> test: replace fireevent with userevent

- src/app/components/AllowanceMenu/index.tsx
- src/app/components/BudgetControl/index.tsx
- src/app/components/ConnectorForm/index.tsx
- src/app/components/PublishersTable/index.tsx
- src/app/components/TransactionsTable/index.tsx
- src/app/router/Popup/Popup.tsx
- src/app/router/Prompt/Prompt.tsx
- src/app/screens/Keysend/index.tsx
- src/app/screens/LNURLPay.tsx
- src/app/screens/LNURLWithdraw.tsx
- src/app/screens/Onboard/Intro/index.tsx
- src/app/screens/Onboard/SetPassword/index.tsx
- src/app/screens/Onboard/TestConnection/index.tsx
- src/app/screens/Options/TestConnection/index.tsx
- src/app/screens/Publisher.tsx
Renamed sat to sats in the UI.
Closes #917
- `chore`: Renamed variable (updating grunt tasks etc; no production code change)
Ran all unit and e2e tests.
(Although not necessary :P)
> chore: rename sat to sats

- src/app/components/Menu/MenuItemButton.tsx
I did some research on different ux approaches to showing an active account and came up with a dot / checkmark.
> style: highlight with dot and checkmark

- src/app/router/Popup/index.tsx
react-toastify styles were missing on the popup
> style: add missing react-toastify css to popup screen

- .github/workflows/playwright.yml
> chore(ci): update yarn-actions

- src/common/lib/api.ts
- src/extension/background-script/actions/accounts/index.ts
- src/extension/background-script/actions/accounts/isUnlocked.js
- src/extension/background-script/actions/lnurl/auth.ts
- src/extension/background-script/router.ts
- src/extension/background-script/state.ts
> refactor(state): isUnlocked handling #652

- src/app/router/Prompt/Prompt.tsx
- src/app/screens/Home/index.tsx
- src/common/lib/msg.ts
- src/common/lib/utils.ts
- src/extension/background-script/actions/accounts/__tests__/add.test.ts
- src/extension/background-script/actions/accounts/__tests__/delete.test.ts
- src/extension/background-script/actions/accounts/__tests__/edit.test.ts
- src/extension/background-script/actions/ln/index.js
- src/extension/background-script/actions/ln/makeInvoice.js
- src/extension/background-script/actions/lnurl/auth.ts
- src/extension/background-script/actions/lnurl/pay.ts
- src/extension/background-script/actions/lnurl/withdraw.ts
- src/extension/background-script/actions/webln/keysendOrPrompt.ts
- src/extension/background-script/actions/webln/makeInvoiceOrPrompt.ts
- src/extension/background-script/actions/webln/sendPaymentOrPrompt.ts
- src/extension/background-script/actions/webln/signMessageOrPrompt.ts
- src/extension/background-script/index.js
- src/extension/content-script/index.js
- src/extension/content-script/setLightningData.ts
- src/extension/ln/webln/index.ts
- src/types.ts
Renamed message `type` to `action`
Closes #759
- `chore`: Renamed variable (updating grunt tasks etc; no production code change)
Ran all unit and e2e tests.
> chore: rename type to action

- src/app/screens/Home/index.tsx
Allow users to switch from the AllowanceView, back to the DefaultView.
#946
> feat: go back to general home from contextual home

- src/app/screens/Accounts/index.tsx
Typo
--
- `chore`: Typo fix
Ran all tests
> chore: rename accountName id

- src/common/lib/api.ts
- src/extension/background-script/actions/accounts/__tests__/lock.test.ts
- src/extension/background-script/actions/accounts/lock.ts
- src/types.ts
- Switch account lock to TS
- Add test
> refactor(account): lock #652

- src/app/screens/Accounts/index.tsx
- src/app/screens/Onboard/TestConnection/index.tsx
- src/app/screens/Options/TestConnection/index.tsx
- src/common/lib/api.ts
- src/extension/background-script/actions/accounts/__tests__/remove.test.ts
- src/extension/background-script/actions/accounts/index.ts
- src/extension/background-script/actions/accounts/remove.ts
- src/extension/background-script/router.ts
- src/types.ts
Renames delete to remove and updates the alert message.
Follows this https://github.com/getAlby/lightning-browser-extension/issues/955#issuecomment-1153553635
Closes #955
- `chore`: Renaming a variable
Ran all tests
> chore: rename delete to remove

- src/app/screens/connectors/NewWallet/index.tsx
- src/i18n/locales/en/common.json
- src/i18n/locales/en/translation.json
[#781](https://github.com/getAlby/lightning-browser-extension/issues/781)
Visual testing by entering current Alby username and incorrect password (to throw create_wallet_error). I wasn't sure how to test the connection_error string here.
> i18n: Translate Toasts on NewWallet Page

- src/app/components/QrcodeScanner/index.tsx
- src/app/screens/connectors/ConnectLnd/index.tsx
- src/app/screens/connectors/ConnectLndHub/index.tsx
- src/app/screens/connectors/NewWallet/index.tsx
- src/i18n/i18nConfig.ts
- src/i18n/locales/en/common.json
- src/i18n/locales/en/components.json
- src/i18n/locales/en/translation.json
Translation mapping for LND & LndHub connectors, and QrcodeScanner component
[#781](https://github.com/getAlby/lightning-browser-extension/issues/781)
Visual validation
> Translate LND & LndHub connectors, and QrcodeScanner component

- src/common/lib/api.ts
- src/extension/background-script/actions/accounts/__tests__/unlock.test.ts
- src/extension/background-script/actions/accounts/unlock.ts
- src/types.ts
> refactor(account): unlock #652

- src/app/context/AuthContext.tsx
#1066 didn't remove the comment
- `chore`
> chore: remove comment

- package.json
- src/extension/background-script/connectors/eclair.ts
- src/extension/background-script/connectors/lnbits.ts
- src/extension/background-script/connectors/lndhub.ts
- src/extension/background-script/connectors/nativelnbits.ts
- src/extension/background-script/connectors/nativelnd.ts
- src/extension/background-script/connectors/nativelndhub.ts
Takes care of expired Alby tokens
#960
Using https://www.charlesproxy.com  
Old school, but worked :D
> fix(lndhub): expired alby token #960

- src/app/components/AllowanceMenu/AllowanceMenu.stories.tsx
- src/app/components/AllowanceMenu/index.test.tsx
- src/app/components/AllowanceMenu/index.tsx
- src/app/components/PublishersTable/PublishersTable.stories.tsx
- src/app/components/PublishersTable/index.tsx
- src/app/screens/Publishers/index.tsx
- src/extension/background-script/actions/allowances/update.js
- src/types.ts
This would fix the issue of not having a fixed type for Allowance id (and publisher id)
[i.e. number while using to update the Dexie DB and string elsewhere]
-
- `chore`: type change
--
Ran all tests manually, adding, updating and deleting an allowance.
> chore: change allowance/publisher id type to number

- src/extension/content-script/batteries/StackOverflow.ts
- src/extension/content-script/batteries/index.ts
Added tipping functionality for StackOverflow
Closes #1063
https://user-images.githubusercontent.com/64399555/175388430-56071da2-567d-485a-b8ef-259897c298bd.mp4
> feat: add tipping for stackoverflow profiles

- src/extension/background-script/state.ts
This reverts commit 4e20d39a4074ffa3ef165d4f3d9b9d42309f652b, reversing
changes made to 73fb320a612077e201f374fa3ba2dfba35731ac0.
For some reason this adding empty acocunts to the list which then break code because i.e. `account.name` does not exist.
> Revert "Merge pull request #1083 from im-adithya/task-zustand-warning"

- src/app/screens/Onboard/Intro/index.tsx
- src/app/screens/Onboard/SetPassword/index.tsx
- src/app/screens/Onboard/TestConnection/index.tsx
- src/app/screens/Options/TestConnection/index.tsx
Fixes #1094
<p>
</p>
<p>
</p>
<p>
</p>
> fix: margin issues

- src/app/components/AccountMenu/index.test.tsx
- src/app/components/AccountMenu/index.tsx
- src/app/components/UserMenu/index.tsx
- src/app/context/AccountContext.tsx
- src/app/router/Options/Options.tsx
- src/app/router/Popup/Popup.tsx
- src/app/router/Prompt/Prompt.tsx
- src/app/router/RequireAuth.tsx
- src/app/router/Welcome/Welcome.tsx
- src/app/screens/Accounts/index.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/Keysend/index.tsx
- src/app/screens/LNURLPay.tsx
- src/app/screens/Options/TestConnection/index.tsx
- src/app/screens/Receive.tsx
- src/app/screens/Settings.tsx
- src/app/screens/Unlock/index.tsx
FInalize renaming of AutoCOntext to AccountContext
1040
- refactor
> refactor: finalize renaming #1040

- src/app/screens/Accounts/index.tsx
- src/i18n/locales/en/translation.json
Follow up to #1012
Refer: https://github.com/getAlby/lightning-browser-extension/pull/1012#pullrequestreview-1012567170
#669
N/A
Checked manually
> feat(i18n): use translations in export account

- src/types.ts
Removed unnecessary omit "args" as MessageDefault doesn't contain args property
--
- `chore`
Ran all tests
> chore: remove unnecessary omit

- src/extension/ln/webln/index.ts
1. add metadata as an optional parameter to the  ```SendPayment``` function
2. code works when metadata is passed or not passed
Tested by making payments with and without passing metadata from the client-side using prototype
> feat: extend webln sendPayment method

- tests/e2e/createWallets.spec.ts
- tests/e2e/helpers/loadExtension.ts
Add a test to open the publishers screen.
> test: publishers screen after wallet creation

- src/extension/background-script/actions/ln/sendPayment.ts
- src/extension/background-script/connectors/lnd.ts
Errors in the LND#sendPayment call have not properly be propagated and the user did not get a proper error message.
For example trying to pay an invoice from another network (e.g. regtest) causes now an error to be shown. 
not sure how to best write a test for this, but it looks good.
> fix: properly propagate errors from LND

- src/app/screens/Settings.tsx
- src/i18n/locales/en/translation.json
I kinda think the `Change the...` is redundant...
> chore: some settings description changes

- src/app/screens/Home/index.tsx
- src/app/screens/Publisher.tsx
- src/extension/background-script/actions/allowances/__tests__/get.test.ts
- src/extension/background-script/actions/allowances/get.ts
- src/extension/background-script/actions/allowances/list.ts
- src/types.ts
Switching allowance/delete to TS
Relates to #989
- `refactor`: Migration to TypeScript
Should add tests, would be done after review
> refactor(allowance): get action

- src/app/components/TransactionsTable/index.test.tsx
- src/app/components/TransactionsTable/index.tsx
- src/app/screens/Home/index.tsx
- src/app/screens/Publisher.tsx
- src/app/screens/connectors/NewWallet/index.tsx
- src/common/lib/api.ts
- src/common/lib/utils.ts
- src/extension/background-script/actions/allowances/__tests__/get.test.ts
- src/extension/background-script/actions/allowances/__tests__/list.test.ts
- src/extension/background-script/actions/ln/index.ts
- src/extension/background-script/actions/ln/invoices.ts
- src/extension/background-script/actions/lnurl/index.ts
- src/extension/background-script/connectors/citadel.ts
- src/extension/background-script/connectors/connector.example
- src/extension/background-script/connectors/connector.interface.ts
- src/extension/background-script/connectors/eclair.ts
- src/extension/background-script/connectors/galoy.ts
- src/extension/background-script/connectors/lnbits.ts
- src/extension/background-script/connectors/lnd.ts
- src/extension/background-script/connectors/lndhub.ts
- src/extension/background-script/router.ts
- src/extension/ln/webln/index.ts
- src/i18n/i18nConfig.ts
- src/i18n/locales/en/translation.json
- src/types.ts
- tests/unit/helpers/i18n.ts
- invoices call for LND
- invoices call for LNDHub
- invoice-tx list to home screen
- tabs to switch between incoming/outgoing txs
- types
#389
- so far only manually
> feat: add getInvoices #389

- package.json
- yarn.lock
Reverts getAlby/lightning-browser-extension#1203
> Revert "Upgrade zustand: 3.7.2 → 4.0.0 (major)"

- src/extension/background-script/connectors/citadel.ts
- src/extension/background-script/connectors/eclair.ts
- src/extension/background-script/connectors/galoy.ts
- src/extension/background-script/connectors/lnbits.ts
As discussed in the community call. Updating the "no supported" message
#389 
- chore
> chore(connector): adjust unsupported message for getInvoices #389

- src/app/screens/connectors/NewWallet/index.tsx
- src/i18n/locales/en/translation.json
- tests/e2e/createWallets.spec.ts
People are not aware that this is sensitive data and share screenshot and videos
Export is now possible from the export function
> chore: remove account export in onboarding

- src/extension/background-script/actions/allowances/__tests__/add.test.ts
- src/extension/background-script/actions/allowances/__tests__/delete.test.ts
- src/extension/background-script/actions/allowances/__tests__/enable.test.ts
- src/extension/background-script/actions/allowances/__tests__/get.test.ts
- src/extension/background-script/actions/allowances/__tests__/list.test.ts
- src/extension/background-script/actions/allowances/__tests__/update.test.ts
- src/extension/background-script/actions/allowances/enable.ts
- src/types.ts
Switching allowance/enable to TS
Relates to #989
- `refactor`: Migration to TypeScript
Added tests
> refactor(allowance): enable action

- src/extension/background-script/actions/lnurl/auth.ts
> chore: add missing import

- src/app/components/AccountMenu/index.test.tsx
- src/app/components/AllowanceMenu/AllowanceMenu.stories.tsx
- src/app/components/AllowanceMenu/index.test.tsx
- src/app/components/AllowanceMenu/index.tsx
- src/app/screens/ConfirmPayment/index.test.tsx
- src/extension/background-script/actions/allowances/update.ts
Fixes #ISSUE-NUMBER
@bumi from our pairing. I can't seem to find the PR number/
Fix displaying and calculating remaining budget for Allowances
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> fix: remaining budget display

- src/app/components/AccountMenu/AccountMenu.stories.tsx
- src/app/components/AccountMenu/index.test.tsx
- src/app/components/AccountMenu/index.tsx
- src/app/components/Navbar/Navbar.stories.tsx
- src/app/components/Navbar/Navbar.tsx
- src/app/context/Providers.tsx
- src/app/router/Options/Options.tsx
- src/app/router/Popup/Popup.tsx
- src/app/router/Prompt/Prompt.tsx
- src/app/router/Welcome/Welcome.tsx
- src/app/screens/Accounts/index.tsx
This is a small refactoring PR:
- wrap all views in `<Providers>` component as all use the same providers
- remove all providers from `Welcome` screen as none of the child components need/read any data from any context
- component `AccountMenu` is already reading the current accountInfo from the `AccountContext` with the hook `useAccount()` 
- => no need to pass the `title` and `balances` via multiple Parent Components as the AccountMenu can read them by itself already
- Fix updating the account name after Editing the name on the Accounts Screen with calling `fetchAccountInfo` from AccountContext
Immediately update account name in all occasions
Only tested manually. Let me know if I can write better tests. i am not familiar with …
> refactor: better context integrations

- README.md
> chore: just to trigger tests

- tests/e2e/createWallets.spec.ts
> test(createWallet): get rid of flaky alby tests

- src/extension/content-script/batteries/GeyserProject.ts
- src/extension/content-script/batteries/index.ts
I have added another battery detector for Geyser crowdfunding projects, you can now fund projects directly with Alby.
No related issue but this was discussed on Twitter with @bumi 
Ran locally and was able to get Alby to detect the lightning address and other attributes on the Geyser website.
I am putting in a PR with Geyser as well the finalize this - it will work currently but I am adding more selectors so that we can use a better avatar and project title as seen in the sceenshots.
> Geyser battery

- src/app/components/Button/index.tsx
- src/app/components/ConfirmOrCancel/index.tsx
- src/app/components/Container.tsx
- src/app/components/ContentMessage/index.tsx
- src/app/components/PublisherCard/index.tsx
- src/app/screens/ConfirmKeysend/index.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/ConfirmSignMessage/index.tsx
- src/app/screens/Enable/index.tsx
- src/app/screens/Home/index.tsx
- src/app/screens/LNURLAuth.tsx
- src/app/screens/LNURLChannel.tsx
- src/app/screens/LNURLPay/index.tsx
- src/app/screens/LNURLWithdraw.tsx
- src/app/screens/MakeInvoice.tsx
Modifies the Container component and uses it for responsiveness.
Extends #1118 
> fix: use container for responsiveness

- src/app/components/AllowanceMenu/index.tsx
- src/app/components/ContentMessage/index.tsx
- src/app/screens/ConfirmKeysend/index.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/LNURLChannel/index.tsx
- src/app/screens/LNURLWithdraw/index.test.tsx
- src/app/screens/LNURLWithdraw/index.tsx
Changes LnurlWithdraw screen to use TextField component
Fixes #1274 
Tested Manually at https://lnurl.fiatjaf.com/
> missing label in LnurlWithdraw screen

- src/app/screens/ConfirmPayment/index.test.tsx
- src/app/screens/LNURLPay/index.tsx
Fixes jest warnings.
Fixes #1229
- `chore`: remove warnings in tests
Ran tests w/o warnings
> fix: jest warnings

- src/app/components/LocaleSwitcher/LocaleSwitcher.tsx
- src/app/context/SettingsContext.tsx
- src/app/router/Welcome/Welcome.tsx
- src/i18n/locales/hi/translation.json
Should replace #869
#743
no
Checked if function is being called on reload
> feat(settings): set locale on mount #743

- src/app/screens/ConfirmPayment/index.tsx
- src/common/lib/utils.ts
- src/extension/background-script/db.ts
- src/extension/background-script/events/index.js
- src/extension/background-script/events/persistMetadata.ts
- src/extension/background-script/events/persistPayments.js
- src/types.ts
feat: store metadata in DB
store metadata in payments table 
covered cases -
1. non-empty invoice valid  metadata
2. non-empty invoice invalid metadata
3. non-empty invoice no metadata
4. empty invoice valid metadata
5. empty invoice invalid metadata
6. empty invoice no metadata
7. validate metadata before making payment
8. allow payments to happen only when metadata is valid
9. no metadata passed is equivalent to valid metadata
updates:
change metadata type to json 
updates:
create new table to store metadata
persist metadata in new table
add additional helpful fields such as AllowanceId, host etc to associate metadata table to other tables
store metadata JSON as well as common attributes in separate column to easily query the metadata
(querying metadata fields + rendering metadata …
> feat: Store metadata in db

- src/app/screens/Receive.tsx
- src/app/screens/Send/index.tsx
- src/i18n/locales/en/translation.json
i18n for screens:
- Send
- Receive
#1283
> feat: i18n for send/receive #1283

- src/app/components/ConfirmOrCancel/index.test.tsx
- src/app/components/ConfirmOrCancel/index.tsx
- src/app/screens/Enable/index.tsx
- src/i18n/locales/en/translation.json
> feat: i18n for enable

- src/app/screens/Publisher.tsx
- src/app/screens/Publishers/index.test.tsx
- src/app/screens/Publishers/index.tsx
- src/i18n/locales/en/translation.json
i18n for screens:
- Publisher
- Publishers
#1283
> feat: i18n for publisher 1283

- src/app/router/Options/Options.tsx
- src/app/router/Welcome/Welcome.tsx
- src/i18n/locales/en/translation.json
i18n for screens:
- Options
#1283
> feat: i18n for options #1283

- src/app/components/AllowanceMenu/index.tsx
- src/app/components/Loading/index.tsx
- src/app/screens/Home/index.tsx
- src/i18n/locales/en/translation.json
i18n for home screen [and the components present in Home Screen]
#1283
> feat: i18n for home

- src/app/screens/LNURLPay/index.tsx
- src/i18n/locales/en/translation.json
i18n translation for the lnurlpay screen.
Tested locally.
> chore: translate lnurlpay screen

- .eslintrc.json
- jest.setup.js
- src/app/screens/LNURLWithdraw/index.test.tsx
- src/common/utils/__tests__/currencyConvert.test.ts
- tests/fixtures/msw/handlers.ts
- tests/unit/helpers/server.ts
Follow up to #1315 
none
- test setup
none
uni tests still working
> test(msw): use general setup for all tests #1302

- src/app/screens/Settings.tsx
- src/app/screens/Unlock/index.tsx
- src/extension/background-script/actions/setup/reset.js
- src/i18n/locales/en/translation.json
- tests/e2e/createWallets.spec.ts
This adds a more descriptive error message and allows the user to reset their accounts to start over
#1169 #401 
Try to unlock with an invalid password
> feat: unlock password reset

- src/app/components/BudgetControl/index.tsx
- src/i18n/locales/en/translation.json
> feat(budgetcontrol): i18n #1311

- src/app/components/SuccessMessage/index.tsx
- src/i18n/locales/en/translation.json
> feat(successmessage): i18n #1311

- src/app/screens/Unlock/index.tsx
> feat(unlock): i18n #1311

- src/app/screens/MakeInvoice.tsx
- src/i18n/locales/en/translation.json
- i18n
- minor if/else refactor
> feat(makeinvoice): i18n #1311

- src/app/screens/Receive/index.test.tsx
- src/app/screens/Receive/index.tsx
- Support trigger Receive/"create invoice" form-submit on "Enter"
- Fix payment status i18n strings #1346
- `fix`
Manually and added a unit-test
> feat(receive): submit form on enter

- src/app/screens/ConfirmSignMessage/index.tsx
- src/i18n/locales/en/translation.json
> feat(confirmsignmessage): i18n #1311

- src/app/screens/ConfirmKeysend/index.tsx
- src/i18n/locales/en/translation.json
> feat(confirmkeysend): i18n #1311

- src/extension/background-script/actions/allowances/add.ts
- src/extension/background-script/actions/allowances/delete.ts
- src/extension/background-script/actions/allowances/enable.ts
- src/extension/background-script/actions/allowances/update.ts
- src/i18n/locales/en/translation.json
Adds i18n to allowance actions.
#1368
Tested in jest
> feat(i18n): allowance actions

- src/app/components/UserMenu/index.tsx
- src/i18n/locales/en/translation.json
Adds i18n to usermenu component.
#1368
> feat(i18n): usermenu component

- src/app/components/CompanionDownloadInfo.tsx
- src/i18n/locales/en/translation.json
Adds i18n to CompanionDownloadInfo component.
#1368
> feat(i18n): CompanionDownloadInfo component

- src/app/screens/Accounts/index.tsx
- src/i18n/locales/en/translation.json
i18n for Account screen
#1283 
> feat: i18n for account screen

- src/extension/background-script/actions/allowances/add.ts
- src/extension/background-script/actions/allowances/delete.ts
- src/extension/background-script/actions/allowances/enable.ts
- src/extension/background-script/actions/allowances/update.ts
- src/i18n/locales/en/translation.json
Reverts getAlby/lightning-browser-extension#1374
> Revert "feat(i18n): allowance actions"

- src/extension/content-script/batteries/SoundCloud.ts
- src/extension/content-script/batteries/helpers.ts
- src/extension/content-script/batteries/index.ts
Added integration for SoundCloud
#1348
https://user-images.githubusercontent.com/64399555/187685931-cea0251d-711d-4085-840d-9ff1cfdef69e.mp4
> SoundCloud Battery

- src/app/screens/ConfirmPayment/index.tsx
- src/i18n/locales/en/translation.json
> feat(confirmpayment): i18n #1311

- src/extension/content-script/batteries/GitHub.ts
- src/extension/content-script/batteries/Reddit.ts
1) Fixes the username issue in Reddit Tipping [currently also shows (1), which indicates the notifications on that page as we use `document.title`]
2) Fixes GitHub URL matcher. Currently, it doesn't show up when we visit `https://github.com/im-adithya/` instead of `https://github.com/im-adithya` (notice ending slash)
> Battery Fixes

- src/app/components/LocaleSwitcher/LocaleSwitcher.tsx
- src/app/components/Setting/index.tsx
- src/app/screens/Settings.tsx
- src/i18n/locales/en/translation.json
Updated copy for language selector in Settings based on user feedback, also added a link to the Weblate for translations, and removed unfinished languages to avoid further confusion. 
#1192 
Ran locally
> refactor: update copy, add link and remove unfinished language selector

- src/extension/content-script/batteries/Mixcloud.ts
- src/extension/content-script/batteries/index.ts
Added integration for Mixcloud
#1348
> Mixcloud Battery

- src/app/components/LocaleSwitcher/LocaleSwitcher.tsx
- src/app/screens/Settings.tsx
- src/i18n/i18nConfig.ts
- add Spanish and Portuguese (Brazil)
- adjust locale select
> feat(i18n): add es and pt_BR

- src/app/components/PublisherCard/index.tsx
- src/app/screens/LNURLPay/index.tsx
The recent PR has changed the prop values in the LNURLPay screen which caused this:
This PR corrects it to this:
> fix: publishercard in lnurlpay screen

- src/manifest.json
- src/manifest.json.development.sample
otherwise it might not be loadable within the site
> fix: add missing inpage script to accessible resource

- src/extension/content-script/batteries/Vida.ts
- src/extension/content-script/batteries/index.ts
Adds Vida battery
#1418 
Here: https://vida.page/kierandnolan
> feat: vida battery

- src/extension/content-script/batteries/LinkTree.ts
- src/extension/content-script/batteries/index.ts
Adds Linktree battery
#1415
Tested Manually.
> feat: linktree battery

- src/app/screens/connectors/ConnectGaloy/index.tsx
Dark mode fix for the Galoy connector that was reported by a user in Telegram.
Ran locally
> fix: dark mode on galoy connector

- src/app/screens/MakeInvoice.tsx
> ConfirmOrCancel i18n fix

- src/extension/background-script/actions/allowances/enable.ts
Updates allowance name/icon on revisiting a website so that we can change if it is broken or old
Fixes #1304
--
> fix: update allowance icon on revisit

- src/extension/content-script/batteries/LinkTree.ts
Fixes linktree battery
Closes #1453
At https://linktr.ee/mike.neumann
> fix: linktree

- src/app/components/AccountMenu/index.test.tsx
- src/app/components/AccountMenu/index.tsx
- src/app/screens/Accounts/index.tsx
- src/app/screens/connectors/NewWallet/index.tsx
- src/i18n/locales/en/translation.json
- src/i18n/locales/es/translation.json
- src/i18n/locales/pt_BR/translation.json
- missing `AccountMenu` translations
- fixing `accounts` edit label
> fix(accounts): i18n related updates

- src/app/screens/LNURLAuth/index.tsx
- src/app/screens/LNURLWithdraw/index.tsx
- LNURLAuth: aligning error-handling with other LNURLActions
- LNURLChannel: is already taking care of this
- LNURLPay: is already taking care of this
#1451
Tested with LNMarkets (see screenshot)
> fix(lnurlwithdraw): display error on prompt #1451

- src/app/components/LocaleSwitcher/LocaleSwitcher.tsx
- src/app/context/SettingsContext.tsx
- src/i18n/i18nConfig.ts
Adding localization for daysjs
Manually
> fix(daysjs): i18n

- src/app/components/PublisherCard/index.tsx
- src/app/screens/Onboard/Intro/features.tsx
Fixes the issue because of which text is being cut off in PublisherCard
Also fixes the excess padding issue when there's no image in PublisherCard
Closes #1499
Manually
> fix: remove unnecessary line height

- src/app/router/Prompt/Prompt.tsx
- src/app/screens/ConfirmSignMessage/index.test.tsx
- src/app/screens/ConfirmSignMessage/index.tsx
Uses navstate in confirmsignmessage
#1457
> chore: align confirmsignmessage to use navstate

- src/app/router/Prompt/Prompt.tsx
- src/app/screens/ConfirmKeysend/index.test.tsx
- src/app/screens/ConfirmKeysend/index.tsx
Uses navstate in confirmkeysend
#1457
> chore: align confirmkeysend to use navstate

- src/app/screens/Home/index.tsx
- src/app/screens/Keysend/index.test.tsx
- src/app/screens/Keysend/index.tsx
- src/app/screens/Send/index.tsx
- src/i18n/locales/en/translation.json
Uses navstate in keysend
Also revamps the screen to use new components
#1457
<p>
</p>
Manually
> chore: align keysend to use navstate

- src/app/context/AccountContext.tsx
Updates the callback to change the sats value after change
Fixes #1514
Tested manually by sending payments and switching accounts
> fix: callback in fetchaccountinfo

- src/app/context/SettingsContext.tsx
- src/common/lib/api.ts
- src/extension/background-script/actions/cache/__tests__/getCurrencyRate.test.ts
- src/extension/background-script/actions/cache/getCurrencyRate.ts
- src/types.ts
Avoid race-condition for useEffect
Fixes #1521
Manually
> fix(settings): avoid race-condition with default value (usd) #1521

- tests/e2e/002-walletFeatures.spec.ts
- add lnurl-auth test
- use unlock for helper for send to ln-address
Add e2e test for LNURL-auth link
> test(e2e): lnurl-auth

- src/extension/content-script/batteries/YouTubeVideo.ts
Looks like (some) users getting a new UI:
Some might still get the old UI.
> fix: did youtube update the UI?

- src/app/screens/connectors/ConnectCitadel/index.tsx
- src/app/screens/connectors/ConnectEclair/index.tsx
- src/app/screens/connectors/ConnectLnbits/index.tsx
- src/app/screens/connectors/ConnectMyNode/index.tsx
- src/app/screens/connectors/ConnectUmbrel/index.tsx
- src/i18n/locales/en/translation.json
- src/i18n/locales/es/translation.json
- src/i18n/locales/pt_BR/translation.json
- tests/e2e/001-createWallets.spec.ts
Title
#1464
- `chore`: i18n
Manually
> chore(i18n): translate missing connectors (part:1)

- src/extension/content-script/batteries/GitHub.ts
Ln Address from location in GitHub
Closes #1056
Manually
> feat: check ln address in location

- src/app/screens/connectors/ConnectGaloy/index.tsx
- src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
- src/app/screens/connectors/ConnectStart9/index.tsx
- src/i18n/locales/en/translation.json
Title
#1464
- `chore`: i18n
Manually
> chore(i18n): translate missing connectors (part:2)

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- mainly adding "Fixes" to the PR template to connect a PR to an existing issue automatically
- minor adjustments
> chore: adjust github templates

- src/app/screens/Home/index.tsx
Prefer matching ln-address info over general origin info
Fixes #1483
Tested on YT with monvol
> fix(home): prefer lndata over allowance in publishercard

- src/app/components/ResultCard/index.tsx
> fix: result card dark theme text

- src/i18n/locales/en/translation.json
Fix wording to match "wallets" in general
Fixes #1262
> fix(welcome): tutorial wording #1262

- src/app/screens/LNURLPay/index.tsx
Removes the failure screen to rollback to error toast
Follow-up to #1446
- `chore`
Manually
> chore: remove failure card

- src/app/components/AllowanceMenu/AllowanceMenu.stories.tsx
- src/app/components/AllowanceMenu/index.test.tsx
- src/app/components/AllowanceMenu/index.tsx
- src/i18n/locales/en/translation.json
- src/i18n/locales/es/translation.json
- src/i18n/locales/pt_BR/translation.json
Adds option to set lnurlAuth for allowances from Publishers screen.
Closes #148
https://user-images.githubusercontent.com/64399555/192765505-d4d6c4d0-ca98-4a7e-97c8-10ff59f317d5.mp4
Manually
> feat(allowance): add option to change lnurlauth

- src/app/screens/Enable/index.tsx
- src/app/screens/LNURLAuth/index.tsx
Disables the action button and adds a spinner to stop clicking it more than once.
Closes #1540
https://user-images.githubusercontent.com/64399555/192997903-504ea9ad-6341-4e70-9c9b-b6d6b3eb9f05.mp4
Manually
> feat: add loading to button in enable and lnurlauth

- src/extension/background-script/connectors/lnbits.ts
Adds invoice fetching support for LNBits
**Note:** We don't pass in `custom_records` as of now, please lmk if there's a way to extract from LNBits invoice response
#46
Manually using LNBits account
> feat: getinvoices for lnbits connector

- src/app/screens/LNURLPay/index.tsx
Removed brackets from success screen
Fixes  #1574
> fix: Remove brackets from success screen

- README.md
Fixed 2 spelling of the README.md file.
Changed reccomend to recommend
and multipe to multiple.
Typo
With Grammarly
> fixed typos of README.md file

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- src/app/components/UserMenu/index.tsx
- src/i18n/locales/en/translation.json
- replaced bitcoin design slack with Telegram (I don't feel like a lot of people are joining us for issue-related topics)
- added a link to the guide to our issue page on Github (no preview available until PR is merged)
- added new help icon to the dropdown (links to guides.getalby.com)
- updated label in feature request template (the old one didn't exist anymore)
> Improvements for issue handling

- src/app/screens/Receive/index.tsx
- src/app/screens/Send/index.tsx
Auto-focuses the first input field in Send / Receive screens to reduce total amount of clicks necessary and improve keyboard usage.
> feat: auto-focus first form field

- src/app/screens/LNURLWithdraw/index.tsx
- src/i18n/locales/en/translation.json
Align the success screen of LNURLWithdraw
#1379
Manually
> feat: use resultcard in lnurlwithdraw

- src/extension/background-script/connectors/lnbits.ts
Avoid balances like `89.99`
Before:
After:
Manually
> fix(connectors): lnbits - avoid balance with decimal places

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Added github bug/feature template forms.
Fixes #1547 
I haven't tested this. I would love to know how to.
> add: bug/feature template forms

- src/app/components/BudgetControl/index.tsx
- src/app/screens/LNURLPay/index.tsx
- src/app/screens/LNURLWithdraw/index.tsx
- src/app/screens/MakeInvoice/index.tsx
> feat: focus currency-input

- src/extension/content-script/batteries/Twitter.ts
Supports twitter URLs that start with `mobile.`, i.e. https://mobile.twitter.com/bumi
Fixes #1661
Here: https://mobile.twitter.com/bumi
> fix: support twitter mobile urls

- src/app/screens/LNURLChannel/index.tsx
- src/i18n/locales/en/translation.json
Align the success screen of LNURLChannel
#1379
Manually
> feat: use resultcard in lnurlchannel

- src/i18n/i18nConfig.ts
fyi @tfriberg
Translated:  
https://hosted.weblate.org/projects/getalby-lightning-browser-extension/getalby-lightning-browser-extension/sv/
> feat(i18n): activate swedish

- src/app/screens/ConfirmKeysend/index.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/ConfirmSignMessage/index.tsx
- src/app/screens/Keysend/index.tsx
- src/app/screens/LNURLAuth/index.tsx
- src/app/screens/LNURLChannel/index.tsx
- src/app/screens/LNURLPay/index.tsx
- src/app/screens/LNURLWithdraw/index.tsx
Replaces `window.close()` with `navigate(-1)`
Fixes #1638
Tested manually
> fix: navigate on send

- src/app/screens/Home/AllowanceView/index.tsx
This is a bug fix for the AllowanceView:
- link to the correct Publisher URL
Follow-up on https://github.com/getAlby/lightning-browser-extension/issues/1359
Manually
> fix(allowance-view): link transaction to correct publisher URL

- src/extension/background-script/connectors/citadel.ts
- src/extension/background-script/connectors/nativecitadel.ts
Will remove the citadel SDK to implement the connector
Step 1: #1314 
- `chore`
Requires testing!
> fix: remove runcitadel sdk dependency

- src/app/screens/connectors/NewWallet/index.tsx
- src/extension/background-script/connectors/lndhub.ts
- webpack.config.js
This helps us to validate that the requests come from the extension.
#1622
> feat: add hmac signature to wallet signup

- src/extension/content-script/batteries/Medium.ts
The site has changed since we updated our battery last time so updated it according to the new UI.
Fixes #1708
Tested here https://maxirosson.medium.com/
> fix: tipping in medium

- src/app/screens/Enable/index.tsx
- src/app/screens/Nostr/ConfirmGetPublicKey.tsx
Decreased spacing for list items in enable screen.
Fixes #1639 
Before
After
> fix: decrease spacing between elements to fit into screen

- package.json
- webpack.config.js
- yarn.lock
this no longer requires the webpack hack
> chore: update lnmessage

- src/extension/content-script/originData.ts
don't score the icons. simply choose the first one
#1743
> fix: remove scorer to simply get the first icon image

- src/app/components/Badge/index.tsx
- src/app/components/PublishersTable/index.tsx
- src/app/screens/Publishers/index.test.tsx
- src/app/screens/Publishers/index.tsx
- src/i18n/locales/en/translation.json
- src/types.ts
Indicates publishers for which lnurl-auth is enabled
Fixes #1534
> feat: add publusher lnurl-auth badge

- src/app/screens/Publishers/websites.json
> added LNCal to Websites screen

- src/extension/background-script/actions/allowances/__tests__/add.test.ts
- src/extension/background-script/actions/allowances/__tests__/delete.test.ts
- src/extension/background-script/actions/allowances/__tests__/enable.test.ts
- src/extension/background-script/actions/allowances/__tests__/get.test.ts
- src/extension/background-script/actions/allowances/__tests__/getById.test.ts
- src/extension/background-script/actions/allowances/__tests__/list.test.ts
- src/extension/background-script/actions/allowances/__tests__/update.test.ts
- src/fixtures/allowances.ts
- src/fixtures/payment.ts
1. extract test fixtures about allowances, add files `src/fixtures/allowances.ts and src/fixtures/payment.ts`
1. edited the file of unit test related to allowances  in folder `src/extension/background-script/actions/allowances/__tests__`
Fixes #1200
- `test`: Test code update
The original unit test still works normally
> test: extract test fixtures about allowances

- src/extension/content-script/batteries/LinkTree.ts
Fixes name and description in LinkTree battery
Fixes #1615
> fix: linktree name and description

- src/extension/content-script/batteries/YouTubeChannel.ts
- src/extension/content-script/batteries/YouTubeVideo.ts
Adds support for new @<channel-name> in yt
Fixes #1790
Manually
> fix: update yt battery to support new @

- static/views/options.html
- static/views/popup.html
- static/views/prompt.html
- static/views/welcome.html
Prevents browser from translating pages.
Fixes #1769
Uploading Screen Recording 2022-12-06 at 2.12.26 PM.mov…
> fix: prevent browser from translating

- src/app/components/SatButtons/index.tsx
This removes the default 100sats option and adds a 25k option. 
100 is easy to type and a rather small amount.
> Add 25k option for the default amounts

- src/app/screens/Publishers/websites.json
Sparkshot seems not active anymore
added Lightsats and LNflip, removed Sparkshot and changed Podverse logo.
Sparkshot seems not active anymore
> added Lightsats and LNflip, removed Sparkshot

- webpack.config.js
Disables report and stats generation during dev mode
- `chore`: internal
Manually
> chore: disable analyzer mode in dev

- .gitignore
- .vscode/settings.json
Improve developer experience in vscode by setting the default formatter and automatically formatting files on save.
(Does not fit guideline)
> chore: add vscode Workspace Settings config

- doc/CONTRIBUTION.md
Added info about branch names and a link to the bitcoin design website (required to get a slack invite)
> docs: add more details to contributon document

- src/i18n/locales/en/translation.json
- tests/e2e/002-walletFeatures.spec.ts
+ https://grammarist.com/spelling/log-in-login/
+ not sure if I've found all occurrences, but it's a start :)
> Log in: two words when it's a verb.

- src/app/screens/Publishers/websites.json
Added Vida to "Website" screen
will test after builds have been created.
> Added Vida to "Website" screen

- src/extension/background-script/actions/ln/__tests__/request.test.ts
- src/extension/background-script/actions/ln/request.ts
- src/extension/background-script/state.ts
Add tests for LN request
Closes https://github.com/getAlby/lightning-browser-extension/issues/1753
> feat: add tests for ln request

- src/extension/ln/webbtc/index.ts
> fix: webbtc should behave like webln

- src/app/components/CompanionDownloadInfo.tsx
- src/app/components/PublisherCard/index.tsx
- src/app/components/toasts/ConnectionErrorToast.tsx
- src/app/components/toasts/LoginFailedToast.tsx
- src/app/screens/Publishers/index.tsx
- src/app/screens/Settings.tsx
- src/app/screens/connectors/NewWallet/index.tsx
- src/i18n/locales/en/translation.json
To explain better what happens here.
> feat(nostr): add link to more info about nostr keys

- src/extension/background-script/actions/webln/sendPaymentOrPrompt.ts
to make sure the budget is bigger than the amount
see: #1910
> chore: use greater than check

- src/extension/background-script/actions/settings/changePassword.ts
- src/extension/background-script/nostr/index.ts
See title
Fixes #1925
Manually
> fix(nostr): re-encrypt nostr key on pw change #1925

- src/app/router/Welcome/Welcome.tsx
- src/i18n/locales/de/translation.json
- src/i18n/locales/en/translation.json
- src/i18n/locales/eo/translation.json
- src/i18n/locales/es/translation.json
- src/i18n/locales/fi/translation.json
- src/i18n/locales/it/translation.json
- src/i18n/locales/nl/translation.json
- src/i18n/locales/sv/translation.json
- src/i18n/locales/tl/translation.json
- tests/e2e/001-createWallets.spec.ts
- remove heading from welcome page
- remove obsolete translations
> fix: remove obsolete translation

- src/app/screens/connectors/AlbyWallet/index.tsx
- src/i18n/locales/en/translation.json
Before: see issue  
After:  
Fixes #1937
manually
> fix(albywallet): forgot password link dark mode and i18n #1937

- src/app/components/Button/index.tsx
- src/i18n/locales/en/translation.json
Minor dark mode button styling and one translation fix
Fixes #1942 
> fix: minor onboarding issues

- src/extension/background-script/connectors/lnd.ts
- src/i18n/locales/en/translation.json
> LND: Requesting invoices via webln.request

- src/common/lib/utils.ts
Make `window.webln` & `window.nostr` work in Kiwi browser.
> fix: improve handling for mobile browsers

- src/app/components/PublisherCard/index.tsx
> fix: cutoff text on publisher card

- src/app/screens/Discover/index.tsx
Improvements for the discover page (spacing, breakpoints, card usage, etc). 
Before:
After:
> fix: improve discover ui

- src/app/components/PublishersTable/index.tsx
Some minor changes to improve the publishers UI (consistency, less rounding, less shadows)
Before:
After:
> fix: publishers ui

- src/app/components/AccountMenu/index.tsx
- src/app/components/Navbar/Navbar.tsx
- src/app/components/Navbar/NavbarLink.tsx
- src/app/components/UserMenu/index.tsx
- Match styles from getalby.com navbar
- Moved account dropdown to the right
- Hide navbar on mobile devices
> feat: improve navigation

- src/app/components/Header/index.tsx
- src/app/components/Navbar/NavbarLink.tsx
Closes #1911 + removes the color from active nav items
> fix: navbar container

- src/app/screens/LNURLPay/index.tsx
Handle status 500 for callback-url
Fixes #1995
Manually
> fix(lnurlpay): handle status 500 for callback url #1995

- src/app/styles/_fonts.scss
Found no reference of this file so I deleted it.
> fix: remove obsolete file

- src/i18n/locales/en/translation.json
I think it is one Nostr key, so we should use singular?
> chore: use singular for the nostr key

- src/app/components/Header/index.tsx
> fix: align header buttons

- src/app/components/AllowanceMenu/index.test.tsx
- src/app/components/AllowanceMenu/index.tsx
Wrapped render in act to avoid errors
- `chore`
Ran `yarn run test:unit src/app/components/AllowanceMenu` without errors
> chore(jest): wrap render in act

- src/i18n/locales/es/translation.json
Update translation for spanish language
> Update translation for spanish language

- src/i18n/locales/es/translation.json
More updated translations for spanish language
> More updated translations for spanish language

- src/app/screens/connectors/AlbyWallet/index.tsx
- src/i18n/locales/en/translation.json
Formats the error message during signup.
Fixes #1967
Manually
> fix: format error in signup

- src/i18n/i18nConfig.ts
- src/i18n/locales/es/translation.json
- src/i18n/locales/it/translation.json
- src/i18n/locales/sv/translation.json
- src/i18n/locales/zh_Hans/translation.json
Fixed language error in permissions menu while using `pt_br`
Fixes #2062 
> fix: pt_br language bug in permissions

- README.md
Fix broken links
fixes Broken Links in 
Fixes: #2081
- `fix`: broken links
> Fix broken links to LNURL in README.md

- src/app/screens/Discover/websites.json
Added Iris.to to Discover page
Fixes #2087
> Added Iris.to

- src/app/screens/Home/DefaultView/index.tsx
Load incoming txs as soon as popup is being opened 
if account is being switched Load incoming
- Fixes #1854
> perf: incoming tab take some seconds to load data

- tests/e2e/002-walletFeatures.spec.ts
Adds e2e test for change password feature
Related: #2075
- `chore`
Ran tests
> chore(e2e): add test for change password

- src/extension/background-script/db.ts
The basis is to save the LN address to the DB. This would allow for saving contact info, autofilling payment recipients, etc. One approach as done here is to create a contacts table to allow for adding further fields to contacts if desired later on, and adding a `contactId` to the payments table. Would love to hear feedback on this approach.
(Partly) Fixes #1965
> feat: create LN address entry in db

- doc/SETUP.md
Updated project structure
Fixes #2117
> docs: add fixtures and i18n to project structure

- src/i18n/i18nConfig.ts
- src/i18n/locales/fi/translation.json
> feat(i18n): support finnish language

- src/i18n/i18nConfig.ts
> feat(i18n): support czech language

- package.json
- yarn.lock
> revert: use html5-qrcode: 2.3.7

- src/extension/ln/nostr/types.ts
The nostr event tags type should be `string[][]`
Verified from [NIP01](https://github.com/nostr-protocol/nips/blob/master/01.md)
> fix: event tags type

- src/app/screens/Accounts/Detail/index.tsx
- src/i18n/locales/en/translation.json
Adds a warning for users to not forget about backing up their keys.
> feat: backup reminder for nostr key

- src/i18n/locales/en/translation.json
- tests/e2e/001-createWallets.spec.ts
> chore: call it alby account

- src/app/screens/Publishers/index.tsx
Add loading spinner to websites page
Fixes #2210
Manually
> feat(Websites): add loading spinner

- src/app/screens/Discover/websites.json
Now, primal.net will appear in Nostr section
Fixes #2206
Manually
> feat: Added primal.net to nostr section

- src/app/screens/connectors/ConnectBtcpay/index.tsx
- src/app/screens/connectors/ConnectCitadel/index.tsx
- src/app/screens/connectors/ConnectCommando/index.tsx
- src/app/screens/connectors/ConnectEclair/index.tsx
- src/app/screens/connectors/ConnectGaloy/index.tsx
- src/app/screens/connectors/ConnectKollider/index.tsx
- src/app/screens/connectors/ConnectLnbits/index.tsx
- src/app/screens/connectors/ConnectLnc/index.tsx
- src/app/screens/connectors/ConnectLnd/index.tsx
- src/app/screens/connectors/ConnectLndHub/index.tsx
- src/app/screens/connectors/ConnectMyNode/index.tsx
- src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
- src/app/screens/connectors/ConnectStart9/index.tsx
- src/app/screens/connectors/ConnectUmbrel/index.tsx
Add autofocus to all connectors first form field
Fixes #2264
Manually
> feat: add connectors form field autofocus

- src/app/components/form/DualCurrencyField/index.tsx
Fixes font colors for range label, especially in dark mode.
> fix: add text style for dark mode

- src/app/router/Options/Options.tsx
- src/app/router/connectorRoutes.tsx
- src/app/screens/connectors/ConnectKollider/index.tsx
- src/i18n/locales/en/translation.json
Adds login and signup screens for Kollider
Fixes #2157
https://user-images.githubusercontent.com/64399555/225724551-10ea6ac5-63a0-4509-aed1-0a2a1536b9f0.mov
Manually.
> feat: add kollider signup screen

- src/extension/background-script/actions/nostr/decryptOrPrompt.ts
--
Fixes messages not being decrypted issue in nostr
On astral
> fix: await decrypt

- src/app/components/Navbar/NavbarLink.tsx
I have added hover effect for the navbar elements to improve the user experience as mentioned in the issue #2259 
Fixes #2259
https://user-images.githubusercontent.com/97289088/230618233-95f65638-feac-419d-90a2-9490e86ad1d4.mp4
I have checked from the browser and I have attached a video regarding that.
> fix(ui): added effect to topnav button

- src/app/components/AccountMenu/index.tsx
Some minor fixes for the new account menu: 
- Removed min-width
- Updated hover color of the dropdown
> fix: accountmenu: updated colors, removed min-width

- src/app/screens/Discover/websites.json
- src/i18n/locales/cs/translation.json
- src/i18n/locales/da/translation.json
- src/i18n/locales/de/translation.json
- src/i18n/locales/en/translation.json
- src/i18n/locales/es/translation.json
- src/i18n/locales/fr/translation.json
- src/i18n/locales/it/translation.json
- src/i18n/locales/mr/translation.json
- src/i18n/locales/pl/translation.json
- src/i18n/locales/pt_BR/translation.json
- src/i18n/locales/ro/translation.json
- src/i18n/locales/ru/translation.json
- src/i18n/locales/sv/translation.json
- src/i18n/locales/uk/translation.json
- src/i18n/locales/zh_Hans/translation.json
- src/i18n/locales/zh_Hant/translation.json
Fixed typos fixed at multiple places in the app.
For eg see below it should be `Entertainment` and not `Entertaiment`.
> Fixed typos fixed at multiple places.

- src/app/screens/connectors/ChooseConnectorPath/index.tsx
- src/i18n/locales/en/translation.json
- tests/e2e/001-createWallets.spec.ts
Updated the instructions on connect your lightning wallet page 
- **from** _"connect your lightning wallet page."_ 
- **to** _"To start using Alby Extension, use Alby Account or connect through your lightning wallet."_
Fixes  #2330
Current Page - 
Updated page -
> [FIX] UX on the connect your lightning wallet page.

- package.json
- tailwind.config.js
- yarn.lock
> fix: removed line clamp plugin (included by default)

- src/extension/background-script/connectors/lnc.ts
Prevent race conditions where the current account has been changed in the meantime.
> fix: use account id from connector directly

- src/app/components/DevMenu/index.tsx
- src/app/components/Hyperlink/index.tsx
- src/app/components/Loading/index.tsx
- src/app/components/Progressbar/index.tsx
- src/app/components/PublishersTable/index.tsx
- src/app/components/QrcodeScanner/index.tsx
- src/app/screens/Send/index.tsx
- src/app/screens/connectors/ConnectLnd/index.tsx
Another attempt to unify color usage across the extension after consulting with @stackingsaunter.
> fix: change link color to blue-600 / blue-700 on hover

- src/app/screens/Home/DefaultView/index.tsx
Handle empty `settleDate`
Fixes #1403
Manually
> fix(home): handle undefined settle date #1403

- src/app/screens/Discover/websites.json
LOFT deposits aren't working anymore and users reporting that support does not respond anymore. Project seems abandoned.
> fix: remove loft

- tests/e2e/001-createWallets.spec.ts
- tests/e2e/002-walletFeatures.spec.ts
- tests/e2e/helpers/loadExtension.ts
Make e2e tests able to run independently, update tests to match new ui.
legend.lnbits.com is down right now so there is one failing test 😢 
Fixes _https://github.com/getAlby/lightning-browser-extension/issues/2321_
> chore: fix e2e tests

- src/manifest.json
Embed inpage scripts also on non-http websites.
> fix: add inpage scripts on non https sites

- src/app/components/Header/index.tsx
> fix: center header

- lint-staged.config.js
Includes package.json to go through prettier
> feat: include package.json in lint config

- tests/e2e/001-createWallets.spec.ts
- tests/e2e/002-walletFeatures.spec.ts
Skips alby e2e tests for the moment
- `chore`
> chore: skip alby wallet tests

- src/extension/providers/alby/index.ts
Change from `func(name, con, config)` to `func({name, con, config})`
> fix: change method signature of alby provider

- src/i18n/i18nConfig.ts
- src/i18n/locales/fi/translation.json
Fixes problems introduced with https://github.com/getAlby/lightning-browser-extension/pull/2412
> fix: remove empty translations, fix i18nConfig

- src/app/components/TipCard/index.tsx
- src/app/components/Tips/index.tsx
Update styles of tipcards to match designs. 
https://www.figma.com/file/AMzMvcwrr2IdunqMakaB8r/navigation%2C-dropdown%2C-receive-onchain-work%2C-connectors%2C-nostr-events?type=design&node-id=348-31792&mode=design&t=UiW9ESSBvGhsS6DN-0
> fix: update darkmode for tipcards

- src/app/screens/Keysend/index.tsx
Cleans up the keysend screen
- remove duplicate node id
- remove box around amount input (similar to the LNURL screen)
- spacing
> fix: update keysend screen

- src/extension/background-script/actions/nostr/helpers.ts
- src/extension/background-script/actions/nostr/signEventOrPrompt.ts
Updated validateEvent with latest nostr-tool version and changes do signEventOrPrompt to return error in case of invalid events
Fixes  #2446
1. call window.nostr.enable()
2. Execute one of the following:
```
const signedEvent = await window.nostr.signEvent(undefined);
const signedEvent = await window.nostr.signEvent({a: 1});
```
> fix: improved validation with latest nostr-tools validateEvent

- src/i18n/locales/eo/translation.json
I have added translation to the missing keys in the esperanto language.
Fixes https://github.com/getAlby/lightning-browser-extension/issues/2344 
- `feat`:  Update translation file for esperanto (non-breaking change which adds functionality)
> [Feature] Update translation file for esperanto

- src/app/components/form/DualCurrencyField/rangeLabel.tsx
- src/i18n/locales/de/translation.json
- src/i18n/locales/en/translation.json
- src/i18n/locales/es/translation.json
- src/i18n/locales/fa/translation.json
- src/i18n/locales/fr/translation.json
- src/i18n/locales/hi/translation.json
- src/i18n/locales/mr/translation.json
- src/i18n/locales/pl/translation.json
- src/i18n/locales/pt_BR/translation.json
- src/i18n/locales/sv/translation.json
- src/i18n/locales/zh_Hans/translation.json
- src/i18n/locales/zh_Hant/translation.json
Min and max are not exclusive (current screen displays you have to send > 1 sat, which is wrong)
> fix: change range label to min / max or equal

- src/app/screens/Accounts/Detail/index.tsx
- src/i18n/locales/en/translation.json
> fix: update account delete prompt

- src/app/screens/Discover/websites.json
Added Nostr.kiwi to website screen
> Added Nostr.kiwi to website screen

- .github/workflows/playwright.yml
Add env variables to E2E test build step, E2E tests still don't work :shrug: but it's a first step to getting them green again...
> fix: e2e test build

- src/app/screens/connectors/ConnectBtcpay/index.tsx
> fix: add fetch adapter for btcpay server

- src/app/screens/Receive/index.tsx
Display LNURL redeem option for all connectors.
> fix: redeem LNURL for all connectors

- src/app/screens/Accounts/Detail/index.tsx
- src/app/screens/Accounts/NostrSettings/index.tsx
- src/app/screens/Accounts/index.tsx
avatar was missing in accounts list, account information and nostr settings screen
> feat: add avatar in accounts list, account settings and nostr settings

- webpack.config.js
Add oAuth credentials for our prod builds (so they run on forks again).
> fix: add production credentials

- src/app/components/form/DualCurrencyField/rangeLabel.tsx
Formats numbers in range label.
> fix: number formatting for range label

- src/extension/background-script/connectors/alby.ts
We want to completely remove this side effect in getInfo() - for now avatar will still get updated but I added a TODO for that one
> fix: remove getInfo side effect in alby connector

- src/app/components/AccountDetailLayout/index.tsx
- src/app/components/Header/index.tsx
- src/app/components/Navbar/Navbar.tsx
> fix: use the same border / surface colors for all elements in header

- src/extension/providers/alby/index.ts
- src/extension/providers/nostr/index.ts
- src/extension/providers/webln/index.ts
set enable after promise is returned so that enabled parameter is upto date
> fix: resolve enable parameter bug

- src/app/components/UserMenu/index.tsx
Adds the wallet menu item to the dropdown menu on smaller screen sizes.
> fix: add wallet menu item on smaller screens

- doc/SETUP.md
Makes it more clear what network is used by default, and that mainnet is more stable.
> docs: make network section more clear

- src/i18n/i18nConfig.ts
> feat: add hi locale

- src/extension/providers/nostr/index.ts
- src/extension/providers/webln/index.ts
change function definitions and return types of events
add restrictions on on and off method, throw error if webln is not enabled
> feat: change function definitions and return types of events

- src/app/router/Popup/Popup.tsx
The QRcode router seems to have gotten lost?
> fix: add missing QR code scanner route

- src/extension/content-script/onendliquid.js
Fix comments on src/extension/content-script/onendliquid.js
Not sure:
> nit: fix comments on onendliquid.js

- src/i18n/i18nConfig.ts
> feat: add thai language

- src/app/components/Alert/index.tsx
Decrease padding in `Alert` component.
> fix: decrease padding in alert component

- src/common/lib/utils.ts
https://t.me/getAlby/10807/10903
> fix: remove setInterval, focus window

- src/app/screens/LNURLPay/index.tsx
- src/common/lib/lnurl.ts
as discussed in: https://github.com/lnurl/luds/pull/234
> chore: remove lnurl-pay description hash check

- src/app/components/BudgetControl/index.tsx
- src/app/components/form/Checkbox.tsx
- src/app/screens/Bitcoin/ConfirmGetAddress/index.tsx
- src/app/screens/ConfirmKeysend/index.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/ConfirmSignMessage/index.tsx
- src/app/screens/Liquid/ConfirmGetAddress.tsx
- src/app/screens/Nostr/Confirm.tsx
Bottom-align checkboxes to remember permissions.
> fix: prompt layout

- src/app/components/ConnectorForm/index.tsx
- src/app/router/Welcome/Welcome.tsx
- src/app/screens/connectors/ConnectEclair/index.tsx
Fixes parts of #2707 which are not covered by #2708 (spacing changes in connectors / welcome flow)
> fix: spacing in connectors / welcome screen

- src/extension/background-script/registerContentScript.ts
Inject into all frames as well so `window` APIs are also available on sites like codepen.io, etc.
> fix: inject content script into all frames

- src/app/screens/Discover/websites.json
remove pinstr and channel.ninja
> chore: remove channel.ninja and pinstr

- src/app/screens/Onboard/Prompt/index.tsx
request comes from public/nostr/onboard which needs to be corrected in prompt 
> fix: correct route in onboard prompt.

- src/i18n/locales/de/translation.json
- src/i18n/locales/en/translation.json
- src/i18n/locales/id/translation.json
- src/i18n/locales/ja/translation.json
- src/i18n/locales/pt_BR/translation.json
- src/i18n/locales/sv/translation.json
- src/i18n/locales/th/translation.json
- src/i18n/locales/zh_Hans/translation.json
- src/i18n/locales/zh_Hant/translation.json
> fix: zeus link in translations

- src/extension/content-script/liquid.js
- src/extension/content-script/webbtc.js
let user don't need to reload to make new call after onboarding fix account caching logic
fixes on onboarding logic
1. make next call after onboarding work without reload
2. make caching work
> fix: fix onboard logic

- src/app/components/Avatar/index.tsx
- src/app/screens/Accounts/NostrSetup/NostrSetup.tsx
- src/app/screens/Receive/index.tsx
- src/i18n/locales/en/translation.json
Address feedback from @stackingsaunter 
- fix: only use white background on qr avatar
- fix: do not allow user to setup nostr again if they already have a key
- chore: minor receive translation changes to prevent orphans
> Fix: UI feedback

- package.json
- yarn.lock
this fixes a version conflict issue with npm install
msw 1.3.0 or greater has support for TS 5.2
https://github.com/mswjs/msw/releases/tag/v1.3.0
otherwise npm install fails
> fix: update msw depedency

- src/app/screens/ReceiveInvoice/index.tsx
Changed the alignment of the create invoice button to the bottom of the screen
Fixes #2786 
tested manually
> fix: Align the create invoice button the bottom of the screen

- src/extension/content-script/liquid.js
- src/extension/content-script/webbtc.js
add on and off event calls for webbtc and liquid
> feat: add on and off calls in webbtc and liquid provider

- package.json
- yarn.lock
> chore: update react-router-dom

- src/extension/background-script/connectors/alby.ts
add user agent in default request options so that sdk can use it for alby connector
> feat: addd user_agent in default request options

- package.json
- yarn.lock
we need to stick with the older version of jest-dom unless this is resolved: https://github.com/testing-library/jest-dom/issues/544
> feat: revert jest-dom plugin

- src/app/screens/OnChainReceive/index.tsx
Directly link to the bitcoin address (instead of the receive page).
> feat: direct link to bitcoin address

- src/app/screens/Home/DefaultView/index.tsx
> fix: transaction list fixes

- src/app/screens/ConfirmPayment/index.tsx
adapt new changes to the container component in the screens
Fixes  #2892 
by making payment
> feat: correct confirm_payment screen

- src/i18n/locales/de/translation.json
- src/i18n/locales/en/translation.json
- src/i18n/locales/pt_BR/translation.json
- src/i18n/locales/sl/translation.json
- src/i18n/locales/sv/translation.json
Update copy on nostr enable screen. (apps can't sign without your permission)
> fix: update copy

- src/app/screens/MakeInvoice/index.tsx
shows an error toast if the invoice creation goes wrong in the prompt
> chore: show toast error on make invoice call

- package.json
- src/app/screens/SendToBitcoinAddress/index.tsx
- src/extension/background-script/connectors/alby.ts
- yarn.lock
> fix: swaps status

- src/app/components/TransactionsTable/TransactionModal.tsx
> fix: add boostagram message to transaction details popup

- src/app/components/PaymentSummary/index.tsx
- src/app/screens/ConfirmKeysend/index.test.tsx
- src/app/screens/ConfirmPayment/index.test.tsx
- src/app/screens/ConfirmPaymentAsync/index.test.tsx
> fix: styles for paymentsummary

- src/app/router/Welcome/Welcome.tsx
- src/app/screens/connectors/ConnectAlby/index.tsx
> fix: on welcome screen heading and connect button

- src/app/screens/Discover/index.tsx
responsive tip cards for smaller screens
before:
after:
> feat: responsive tip cards

- src/extension/background-script/connectors/commando.ts
> fix: core-lightning apis

- src/app/screens/connectors/ChooseConnectorPath/index.tsx
voltage connector is broken from welcome screen
> feat: fix voltage connector through welcome screen

- src/app/screens/Accounts/GenerateMnemonic/new.tsx
responsive generate mnemonic page
before:
after:
> feat: responsive master key image

- src/extension/inpage-script/index.js
- src/extension/providers/alby/index.ts
> feat: use separate instances to avoid provider being invaded by other wallets

- src/extension/background-script/connectors/galoy.ts
Using the returned preImage when the payment is settled intraLedger.
Maintaining the compatibility with the bitcoin Jungle wallet which still doesn't return the preimage for intraledger payments.
Fixes #2946
Tested manually in Firefox / LibreWolf.
> fix: return preimage for intraledger payments in galoy connector

- src/app/components/Navbar/Navbar.tsx
not to allow text to split up on next line in navigation
> chore: not to allow text to split up on next line in navigation

- src/i18n/locales/de/translation.json
> feat: rever product name in german translations

- src/extension/background-script/actions/accounts/get.ts
> fix: card show conditional

- src/common/lib/utils.ts
> fix: ios prompt

- .vscode/settings.json
https://stackoverflow.com/questions/77637621/vscode-workspace-settings-change-on-its-own
> fix: update vscode config

- src/extension/background-script/connectors/alby.ts
Removes duplicated `invoices:read` scope
- `chore`: Repetition fix, doesn't change anything for the end user
> chore: remove duplicate scope

- src/app/components/TransactionsTable/index.tsx
- src/app/screens/Home/AllowanceView/index.tsx
- src/app/screens/Home/DefaultView/index.tsx
- src/app/screens/Publishers/Detail/index.tsx
- src/app/screens/Transactions/index.tsx
- src/i18n/locales/en/translation.json
Simplifying layouts & fixing margins on homescreen.
> fix: simplify styles & fix margins on homescreen

- package.json
- yarn.lock
> chore: update js-sdk

- src/app/components/SitePreferences/index.tsx
- src/app/screens/Nostr/ConfirmSignMessage.tsx
- src/i18n/locales/en/translation.json
> feat: minor ui changes

- src/i18n/locales/en/translation.json
> fix: generic permission translations

- src/app/screens/connectors/ConnectNWC/index.tsx
It contains senstive data and should not be seen by anybody
> chore: nwc connect string as password field

- src/manifest.json
remove identity api permissions, it was replaced by tabs api to get oauth tokens 
> fix: remove identity api permissions

- package.json
- src/extension/background-script/connectors/nwc.ts
- yarn.lock
> feat: add sign message

- src/extension/background-script/connectors/lndhub.ts
add custom records for outgoing payments for lndhub
> feat: add custom records in outgoing payments in lndhub

- src/app/components/Badge/index.tsx
- src/app/components/BadgesList/index.tsx
- src/app/components/SitePreferences/index.tsx
> fix: fix-badges

- src/extension/background-script/actions/nostr/enable.ts
add app data event in reasonable kind. avoids repeating popup on primal
> feat: add app data event in reasonable set of permissions

- src/app/components/Alert/index.tsx
update alert dialog designs  as per https://www.figma.com/design/LP96uJXiN2ULQuHyfKaklF/%F0%9F%90%9D--Alby-Browser-Extension?node-id=2174-27616&t=K1Ad2GVGVKmNRch7-0
> feat: update alert dialog designs

- src/app/screens/Nostr/ConfirmSignMessage.tsx
- src/extension/providers/nostr/types.ts
- src/i18n/locales/en/translation.json
return empty description for upload chunk event. as it returns a quite lengthy content
> feat: return empty description for upload chunk event

- src/i18n/locales/en/translation.json
https://github.com/nostr-protocol/nips?tab=readme-ov-file#event-kinds
> chore: add repost kind to english translation

- src/app/screens/Accounts/Detail/index.tsx
Minor fixes before the release
- Link directly to lightning address settings instead of the general settings page
> fix: minor bugfixes before release

- src/app/screens/Home/DefaultView/index.tsx
upload migration link for alby lndhub users
> feat: link migration guide

- src/app/components/AccountMenu/index.test.tsx
- src/app/components/AccountMenu/index.tsx
- tailwind.config.js
> feat: account menu makeover

- src/extension/background-script/connectors/lndhub.ts
show lndhub error messages from response
> feat: proper error messages for lndhub

- src/app/screens/Send/index.tsx
- src/common/lib/lnurl.ts
> proper error handling for bip353 dns addresses from phoenix + self hosted dns addresses

- src/extension/content-script/batteries/Twitter.ts
> fix: twitter battery

- src/app/components/TransactionsTable/index.tsx
> fix: align no transactions copy to center

- README.md
> fix: l402 link

- src/app/components/Avatar/index.tsx
fix avatar position in qr code
> fix: avatar position from qr code

- src/app/screens/Home/DefaultView/index.tsx
Reloads the npub when the account has changed.
> fix: reload npub when account has been changed

- src/i18n/locales/de/translation.json
remove brand name translations from de/translation.json
> Translated using Weblate (German)

- package.json
- yarn.lock
in lower versions ci specs stuck at yarn install
> fix: ci specs via updating puppeteer

- src/i18n/i18nConfig.ts
add ukrainian locale to extension
> feat: add ukrainian locale
