getAlby/lightning-browser-extension

- src/stories/Steps.stories.js
This fixes: `You should not use <Link> outside a <Router>`.
> fix: add a react-router decorator

- .storybook/preview.js
- src/stories/Onboard.stories.js
- src/stories/Transactions.stories.js
Onboarding screens we're not shown anymore inside Storybook because of a webextension-polyfill error: 'Error: This script should only be loaded in a browser extension.'
> fix: stories that use webextension-polyfill are broken

- src/app/components/Collapse.tsx
- src/app/components/Form/CurrencyInput.tsx
- src/app/screens/ConfirmPayment/index.jsx
- CurrencyInput should only support satoshi's for now.
- (visual improvement) The collapse component was cutting of the input border. Now it will apply overflow:hidden styles only during transition.
> Refactor currency input & collapse

- src/app/components/Navbar/NavbarLink.tsx
- src/app/components/Shared/tabs.jsx
- src/app/components/button.tsx
- src/app/components/card.jsx
- src/app/screens/Enable/index.jsx
- src/app/screens/Onboard/ConnectLND/index.jsx
- src/app/screens/Onboard/Intro/faqs.jsx
- src/app/screens/Onboard/Intro/features.jsx
- src/app/screens/Onboard/LastStep/index.jsx
- src/app/screens/Onboard/SetPassword/index.jsx
- src/app/screens/Onboard/TestConnection/index.jsx
- src/app/styles/index.css
For some reason chrome adds `font-size: 75%` to a browser extension.
This PR now makes the use of the class "text-base" redundant, as a font will be the size of 1rem by default now (as it should be).
> Prevent font-scaling by Chrome (making text-base obsolete)

- package.json
- src/app/router/Prompt/Prompt.jsx
- src/app/screens/LNURLAuth.tsx
- src/common/lib/utils.js
- src/extension/background-script/actions/ln/signMessage.js
- src/extension/background-script/actions/lnurl/index.ts
- src/extension/background-script/connectors/lnd.js
- src/extension/background-script/db.js
- src/extension/background-script/events/index.js
- src/extension/background-script/events/notifications.js
- src/extension/background-script/router.js
- src/extension/inpage-script/index.js
- yarn.lock
some services where this can be tested: https://github.com/fiatjaf/awesome-lnurl#lnurl-auth
> LNURL-auth support

- src/app/components/steps.jsx
- src/app/router/Welcome/Welcome.jsx
- src/stories/Steps.stories.js
This adds support for steps without links and also removes step links from the onboarding screens.
> Steps without links

- src/extension/background-script/actions/ln/makeInvoice.js
This PR fixes an error when a service creates an invoice with no memo field, for instance via WebLN: `var payreq = await webln.makeInvoice(parseInt(amount));`.
As per WebLN spec, memo field is optional but backends like lnbits require a memo.
> set default memo for invoice

- src/app/screens/Home/index.jsx
- src/extension/background-script/actions/allowances/enable.js
- src/extension/background-script/actions/setup/setIcon.js
- src/extension/background-script/index.js
- src/extension/content-script/batteries/Monetization.ts
- src/extension/content-script/batteries/Twitter.ts
- src/extension/content-script/batteries/YouTubeVideo.ts
- src/extension/content-script/batteries/index.ts
- src/extension/content-script/index.js
- src/extension/content-script/setLightningData.ts
- src/manifest.json
The content script listens for messages (send from the home screen) with the type “lightningData”. 
It will async grab the data and send it back to the Home screen.
Benefits:
- Currently when lightning data wasn't directly available when opening the popup, the popup will only be updated after re-opening it. With this change, **the popup screen will be live updated** once the lightning data is available.
- No global window properties.
> [Proposal] Use messaging to get lightning data

- src/app/components/BalanceCard/index.tsx
For the conversion, I tried to orient myself on [AllowanceMenu](https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/components/AllowanceMenu/index.tsx)
But it's a bit inconsistent since [Badge](https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/components/Badge/index.tsx) makes the default export in the function instead of the end.
If there is some room for improvement, just tell me :)
> convert BalanceCard to tsx

- src/app/screens/Onboard/ConnectLndHub/index.tsx
- src/app/screens/Onboard/NewWallet/index.tsx
I noticed that in the onboarding section the instructions for LNDHub are styled differently than the instructions for the other options. This might be intentional but I don't think it is. The LNDHub instructions are smaller and have no margin, the other ```p``` elements are all styled with ```mt-6``` and no text size defined. It's a small difference but noticeable I think. All I did was change the styling to match the other screens so that it is uniform.
Here are screenshots of what I mean:
Current LNDHub styling: 
Styling of other instruction elements:
New LNDHub styling:
I also just added capitalization and punctuation for this sentence. I know these are small changes but I think eventually we will want the whole interface to be super polished like this.
Another side note is that there …
> Fix styling to match other screens and some grammar updates

- src/extension/background-script/index.js
This allows to easily access important objects from the background script console.
e.g.
debugAlby.state.getState().accounts gives you the list of accounts
debugAlby.connectors gives ja access to the connector classes
this helps with quickly testing certain changes in a REPL.
> Add optional debug mode

- .babelrc
- package.json
- yarn.lock
- Remove unnecessary polyfills:
Those features already got accepted in ES2018 and are included in @babel/preset-env.
- Remove certain unused dev deps.
> Remove unnecessary polyfills and unused deps

- src/app/screens/Unlock/index.jsx
All of the other buttons within the app have capitalization, currently the unlock button is lowercase. I think it looks more official and inline with the rest of the styles if it is also capitalized.
Before:
After:
> Capitalize Unlock button

- src/extension/content-script/batteries/BitcoinTvVideo.ts
- src/extension/content-script/batteries/Peertube.ts
- src/extension/content-script/batteries/index.ts
This loads lightning data from the BitcoinTV video or channel descriptions and allows tipping from the Alby popup.
To load the data one additional API request is made to BitcoinTV.
> Add BitcoinTV enhancement

- src/app/router/Welcome/Welcome.jsx
- src/app/screens/Onboard/ChooseConnector/index.tsx
Refactor the current route object to be used with the new useRoutes hook.
Then we don't need to manually map the route object into <Routes /> & <Route /> anymore.
Also fixes: #479
> feat: use the new useroutes hook

- src/app/components/TransactionsTable/index.tsx
- src/app/screens/Home/index.jsx
- src/extension/background-script/actions/payments/all.js
Related to issue #310 I limited the number of transactions displaying in the popup to the most recent 10. I also updated the header to say 'Recent Transactions' so it is more clear that it does not include all of them. I just picked the number 10 but we can change it if everyone thinks that is too short, maybe 21 would be better?
> Limit tx history in popup to most recent 10

- src/app/context/AuthContext.tsx
this asynchronously loads the balance and account info after unlocking the accounts.
This fixes a bug that the balance is not shown directly after unlocking the popup.
> Load account info after unlocking

- src/extension/inpage-script/index.js
This allows Alby to load lightning addresses from links like:
```
<a href="lightning:you@getalby.com">send sats</a>
```
> Extract lightning addresses from lightning links

- src/app/components/Button/index.tsx
- src/app/screens/LNURLPay.tsx
- src/app/screens/MakeInvoice.tsx
As requested in #529, I have removed the slider on the sending sats screen. I replaced it with 4 buttons with pre-determined satoshi amounts for each: 10, 100, 1000 and 10000. For the functionality I made it so that when you click each button it adds the satoshi amount to the input, I thought this may be useful rather than only allowing for the number to be set once.
What does everyone think about this?
Screenshot:
I think there is another screen I will have to adjust but I thought I would get feedback on this first and if everyone likes it then I can update the other one as well.
> Replace slider with sat amount buttons when sending

- src/app/components/AccountMenu/index.tsx
- src/app/context/AuthContext.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/LNURLPay.tsx
- src/app/screens/Receive.tsx
Currently after sending a payment with webln or lnurl pay, the balance isn't directly updated.
Current:
Scenario: Tipping on Twitter -> Balance stays the same until reopening the popup.
Scenario: Deposit sats on Kollider -> Prompt appears to make a payment, after payment, the prompt closes. When opening the popup, it first shows the old cached balance and then starts to fetch the new balance.
Desired:
Scenario: Tipping on Twitter -> Balance directly updates after a successful payment.
Scenario: Deposit sats on Kollider -> Prompt appears to make a payment, after payment, the prompt closes. When opening the popup, it directly shows the new balance.
> feat: update balance info after payment

- src/app/components/PaymentSummary.tsx
- src/app/screens/Onboard/ConnectLnd/index.tsx
> Fix macaroon text in dark mode

- src/app/screens/Onboard/ChooseConnector/index.tsx
@bumi wanted to have all on one row instead of having 1 connector by itself.
> Change grid to allow 5 connectors per row

- src/app/screens/LNURLPay.tsx
Current Scenario 1:
- On the send screen, I'm pasting in: bumi@getalby.com
The details screen shows: _Send payment to: getalby.com_
Paying a few sats shows a notification: _Paid x sats to Alby_
Desired Scenario 1:
- On the send screen, I'm pasting in: bumi@getalby.com
The details screen shows: _Send payment to: bumi@getalby.com_
Paying a few sats shows a notification: _Paid x sats to bumi@getalby.com_
What's currently also weird is that "Send payment to:" is using `details.domain` while the notification uses: `metadata.name`, I think they should use the same info.
> Improve LNURL-Pay notification

- README.md
- src/common/lib/lnurl.ts
- src/extension/content-script/batteries/VimeoVideo.ts
- src/extension/content-script/batteries/index.ts
add tips on vimeo: here's demo video: https://vimeo.com/670055676
also fixed a strange bug that was adding these characters while parsing lightningaddress to lnurlp url `https://lntxbot.com/.well-known/lnurlp/%EF%B8%8Fpseudozach`. this was causing lnurlp tips on youtube/vimeo to fail silently.
> add vimeo tips

- src/app/components/PublisherCard/index.tsx
- src/app/screens/Home/index.jsx
- src/app/screens/LNURLPay.tsx
- tailwind.config.js
I think the PublisherCard is unnecessary in the LNURLPay screen and takes too much space.
(Currently you'd have to scroll to see the confirm button).
My preference goes to solely using it for contextual info on the Home screen.
Before:
After:
> Proposal: improved lnurlpay screen

- src/app/screens/Onboard/ConnectEclair/index.tsx
- src/app/screens/Onboard/ConnectLnbits/index.tsx
- src/app/screens/Onboard/ConnectLnd/index.tsx
- src/app/screens/Onboard/ConnectLndHub/index.tsx
- src/app/screens/Onboard/SetPassword/index.jsx
- src/app/screens/Receive.tsx
- src/app/screens/Send.tsx
Associating a `<label>` with an `<input>` element offers some major advantages:
- The label text is not only visually associated with its corresponding text input; it is programmatically associated with it too. This means that, for example, a screen reader will read out the label when the user is focused on the form input, making it easier for an assistive technology user to understand what data should be entered.
- When a user clicks or touches/taps a label, the browser passes the focus to its associated input (the resulting event is also raised for the input). That increased hit area for focusing the input provides an advantage to anyone trying to activate it — including those using a touch-screen device.
Thanks to @escapedcat I did a double-check on this and noticed we were still …
> feat: associate labels with its inputs (A11Y)

- src/app/screens/Home/index.jsx
Just like the DefaultView, the AllowanceView should show some info when there are no transactions yet.
Before:
After:
> Allowance empty screen design

- src/app/screens/Onboard/NewWallet/index.tsx
- webpack.config.js
With this change we create Alby accounts and LndHub compatible wallets.
This also means that the `NewWallet` component no longer works with default lndhub instances.
Do you think we should still support those?
> Use new Alby hosted wallets

- src/app/components/AllowanceMenu/index.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/LNURLPay.tsx
- src/app/screens/MakeInvoice.tsx
Inputs are currently using mixed types of number / undefined.
We should handle everything as a string (during input handling) and convert to number in the appropriate places (api's)
Results:
No more clumsy onChange handlers / falling back on undefined when empty.
> refactor: use html input correctly

- .husky/commit-msg
- README.md
- commitlint.config.js
- package.json
- yarn.lock
Fixes:  https://github.com/getAlby/lightning-browser-extension/issues/612
add commitment linter
setup pre-commit hook ```commit-msg`` using husky
update readme
when commit message doesn't follow commit conventions
when commit message follows commit conventions
> feat(commitlint): add commitlint linter to follow conventional commit specifications

- src/app/components/AccountMenu/index.tsx
- src/app/context/AccountsContext.tsx
- src/app/context/AuthContext.tsx
- src/app/router/Options/Options.tsx
- src/app/router/Popup/Popup.tsx
- src/app/screens/Accounts.tsx
- src/app/screens/Options/TestConnection/index.tsx
Create an Accounts context so accounts state can be used across multiple components easily.
For e.g. when an account get's deleted, it should resemble this in the Accounts list on the accounts screen but also in the AccountsMenu.
> feat: accounts context (updating accounts troughout the whole app)

- src/app/components/CompanionDownloadInfo.tsx
- src/app/screens/Onboard/ConnectLnd/index.tsx
- src/app/screens/Onboard/ConnectLndHub/index.tsx
- src/manifest.json
On chrome based browsers we can not request permissions on they fly.
Requesting the native messaging permission requires a restart
This would kick the user out of the onboarding process.
To work around this we now always require the native messaging permission.
> chore: always require native messaging permission

- src/app/components/Form/Input/index.tsx
- src/app/components/Form/TextField.tsx
- src/app/screens/Onboard/ConnectLnd/index.tsx
- src/app/screens/Onboard/ConnectLndHub/index.tsx
Fixes #693 
Describe the changes you have made in this PR -
I added a form validation pattern for lndhub and lnd to specify requiring lndhub:// and https:// respectively
Screenshots of the changes (If any) -
How Has This Been Tested?
[x] Test A: tried connecting to fake node url starting with: no prefix, http, https, http:// => failed all. tried connecting to fake node url starting with https:// => passed check but didn't connect because credentials were invalid.
[x] Test B: tried connecting to real node url starting with: no prefix, http, https, http:// => failed all. tried connecting to real node url starting with https:// => passed check and connected with valid credentials.
> fix: added pattern and title to TextField and Input for form validation

- tsconfig.json
- Config fix (non-breaking change which fixes an issue)
Update tsconfig to avoid warning  
Thanks @pavanjoshi914 for noticing
`yarn dev` & `yarn build` still working fine
> chore: switch outdir to avoid allowjs overwrite warning

- src/app/components/AllowanceMenu/index.tsx
- src/app/screens/Accounts/index.tsx
Modals triggered from a `<Menu />` currently don't receive focus.
This is because @headless-ui/menu restores focus after closing a menu, to the button that opened it.
There is currently no way to change this behavior so a hack is needed.
More info + added comment: https://github.com/tailwindlabs/headlessui/issues/259
Thanks @escapedcat for noticing it.
> fix: react modals should get focus after opening

- src/extension/background-script/connectors/lndhub.ts
This is a slight bug in the LNDhub connector's keysend function because of confusion between LND's / LNDhub.go's API.
[LNDhub API reference](https://github.com/getAlby/lndhub.go/blob/main/controllers/keysend.ctrl.go#L30)
Custom records should not be hex encoded here.
Tested on amboss.space billboard with webLN.
> fix: lndhub keysend bugs

- src/app/components/AccountMenu/index.tsx
- src/app/components/Menu/MenuItemButton.tsx
You should not be able to quickly jump between accounts, while it was still fetching a previous account.
This currently leads to bugs, showing the wrong balance for e.g. after fastly switching between different accounts.
> fix: prevent switching accounts while in progress

- src/app/screens/Home/index.tsx
Currently, if you are on a website that has an allowance it will shortly render the DefaultView before showing the AllowanceView. Although it's a split second, this looks buggy / messy thus it would be better to wait for the allowance to be loaded (which is really fast).
> fix: default screen shortly rendered before the allowance view

- src/app/screens/Unlock/index.tsx
Removed backgound and shadow from the unlock screen. Those should be decided by the background styling from the prompt template.
Before:
After:
> fix: incorrect unlock styling in prompt

- src/app/router/RequireAuth.tsx
Upon opening the extension or visiting a page in the options, for a few ms a loading indicator is shown in the top left.
This is currently shown upon identifying whether the extension is locked or not. Because this loads so fast it's smoother to just render nothing at all and show the app once ready.
> refactor: smoother app loading

- src/app/components/Button/Button.stories.tsx
- src/app/components/Button/index.tsx
- src/app/components/SatButtons/index.tsx
- src/app/screens/Accounts/index.tsx
- src/app/screens/Receive.tsx
Fixes #727 
- Added a `small` prop to `Button` which changes the padding from `px-7 py-2` to `px-4 py-1`
- Changed `SatButtons` component to use `grid` and `grid-rows-2 lg:grid-rows-1` instead of `flex` for layout
- Before (using chrome on linux) 
- After (using chrome on linux) 
I tested this locally on Firefox and Brave (chrome) and I was able to reproduce and fix the issue.
I was not able to test this on windows since I do no have access to a windows pc.
> fix: pre-defined amount buttons text wrapping

- src/app/components/Button/index.tsx
- src/app/components/IconButton/index.tsx
- src/app/components/LinkButton/index.tsx
Currently the borders from buttons are slightly lighter than the borders from inputs.
This looks a bit weird for e.g. when placing the sat buttons below an input.
> fix: button border should match input border color

- src/app/components/AccountMenu/index.test.tsx
- src/app/components/AccountMenu/index.tsx
- src/app/components/Navbar/Navbar.tsx
- src/app/router/Prompt/Prompt.tsx
Fixes #675
You can now see from the prompt which account is active and also switch your account.
Previously this was unclear.
We now have a more flexible `<Navbar />` that will show an "advanced" version by default. Meaning it will include a user menu and show advanced `<AccountMenu />` options. For the prompt screen I added the improved `<Navbar />` and disabled the advanced prop so it will just show a simplified account menu, that allows you to switch.
> feat: AccountMenu in prompts

- src/app/components/form/Input/index.tsx
- src/app/components/form/TextField.tsx
- src/app/screens/Onboard/TestConnection/index.tsx
- src/app/screens/Options/TestConnection/index.tsx
- src/app/screens/connectors/NewWallet/index.tsx
- src/types.ts
This PR changes the signup for a new alby account. 
We make it clear that the user gets an account on getalby.com and we require an email and a password. 
The user now can also directly create a lightning address during the signup. 
> feat: new wallet account creation with lightning address

- package.json
- src/extension/background-script/connectors/citadel.ts
- yarn.lock
This updates the Citadel SDK and makes a minor change that is required to support Core Lightning (previously called c-lightning) on Citadel in the future.
I manually ensured everything was still working correctly when connected to my local Citadel.
> fix: update citadel sdk for core lightning support

- src/app/components/AccountMenu/AccountMenu.stories.tsx
- src/app/components/AccountMenu/index.test.tsx
- src/app/components/AccountMenu/index.tsx
- src/app/components/Navbar/Navbar.tsx
- src/app/router/Prompt/Prompt.tsx
I removed the need to include a complete `<Navbar /`> if you only need an AccountMenu and made use of substring to give the title a max length (as used in other routers).
This also removes the need for `showAccountMenuOptions` & `showUserMenu` props on the Navbar.
Before:
After:
> fix: accountmenu taking too much height in prompts

- .husky/pre-commit
- lint-staged.config.js
- package.json
The typescript compiler currently checks all ts files on pre-committing. This should just be the staged files.
> chore: lint only staged files

- src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
Updated some import statements as suggested by @dylancom in PR #777 
Ran locally to ensure new imports work
> refactor: imports

- src/common/lib/utils.ts
I think message.args is optional but currently we would add a `args=JSON.stringify(undefined)`
to the prompt URL.
This change only adds the param to the prompt URL if persent.
This might have been a bug introduced by changing how we create the query-string
(in https://github.com/getAlby/lightning-browser-extension/pull/786/files#diff-6aa3c99dd75ad2803ee2a158c3686f6f611f1bbaa59183f9648b97b8cf7abc10L33)
> fix: set prompt search params only if defined

- src/extension/content-script/batteries/Twitter.ts
Fixes #814 
Add the `location` to the data returned from `getUserData`. It is only available on the profile page. In the battery function, we screen for the zap emoji, if `location` was passed in the `userData` object.
I tested in Chrome and Firefox by loading the extension in dev mode.
> feat: scan twitter location for lightning address

- src/app/components/Header/index.tsx
- src/app/components/form/Input/index.tsx
- src/app/components/form/TextField.tsx
- src/app/screens/Send.tsx
- Center align the title in `<Header />` component
- Make scanning a QR code to paste an invoice part of the invoice field.
_The principle of proximity states that items close together are likely to be perceived as part of the same group._ 
Currently it's a button that you easily miss / loses context.
(Inspired by MetaMask)
Before:
After:
> feat: improve send screen UX

- src/app/components/TransactionsTable/index.tsx
- src/types.ts
Fixes #810 
Added the transaction fee information to the transaction detail view.
Sent a tx, checked the value of the fee in the `object` and verify that it displays in the UI.
> feat: add fee amount to tx table

- src/app/screens/Send.tsx
If you currently press "enter" after typing something into the invoice field, the QR Code scanner opens.
(While it should submit the form)
> fix: pressing enter in send screen opens qr code scanner

- src/app/components/ConnectorForm/index.tsx
- src/app/screens/connectors/ConnectUmbrel/index.tsx
Fixes #686
This PR allows us to add an optional video for every connector and adds the first video for the Umbrel connector. If none is provided we still have the fallback to the sats symbol (like it was before). 
Tested on Firefox.
> feat: explanatory videos for account setup

- src/app/components/ConfirmOrCancel/index.tsx
- src/app/components/PublisherCard/index.tsx
- src/app/router/Popup/Popup.tsx
- src/app/screens/LNURLPay.tsx
- src/app/styles/index.css
- Removed the card style from the send screen as it uses a lot of space.
- Smaller avatar.
- Visually hide scrollbar as in most extensions.
Before:
After:
> feat: send screen above the fold

- src/app/router/connectorRoutes.tsx
- src/app/screens/connectors/NewWallet/index.tsx
Change text for the Alby wallet connector to emphansize less on creating a new account. 
Users can now also login to existing accounts via email/password.
- non-breaking change which adds functionality)
> Text update to refect users can now also login to their getalby.com accounts

- src/manifest.json
- src/manifest.json.development.sample
added default shortcut command. super simple, just executes the browser action of opening Alby's popup with the command Alt+Shift+A by default on install.
Uninstalled, reinstalled in chrome and firefox, installs with keyboard shortcut by default. 
- [ x ] My code follows the style guidelines of this project and performed a self-review of my own code
- [ x ] New and existing tests pass locally with my changes
- [ x ] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)
> added default shortcut command

- src/app/screens/connectors/NewWallet/index.tsx
Change Alby success text to be more universal for login and wallet creation
Fixes #860
> Update success message for Alby wallet login/creation

- src/app/context/AuthContext.tsx
Fixes #874
After setting a password during the onboarding, the status becomes "unlocked". Upon refreshing a screen during the onboarding, this will result in an infinite loop (welcome redirecting to options and vice versa) 
This bug seems to have been introduced by: https://github.com/getAlby/lightning-browser-extension/commit/7d17db559c2a85b943d4554ff161adb815fba606
Thanks to @secondl1ght for catching this!
> fix: infinite loop upon refreshing the choose connector screen

- src/app/screens/ConfirmKeysend/index.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/ConfirmSignMessage/index.tsx
- src/app/screens/Enable/index.tsx
- src/app/screens/LNURLAuth.tsx
- src/app/screens/LNURLPay.tsx
- src/app/screens/LNURLWithdraw.tsx
- src/app/screens/MakeInvoice.tsx
- src/common/constants.ts
- src/common/lib/utils.ts
- src/extension/inpage-script/index.js
Fixes #866
When the user closes a prompt or clicks "cancel", an alert will pop up with error: ${message}.
To handle types of errors differently I started to introduce constants so we can identify errors and handle them accordingly.
In this case preventing to show an alert to the user.
> fix: error alert after closing prompt

- src/extension/background-script/actions/allowances/enable.js
- src/extension/background-script/state.ts
During the enable() call we did not check if Alby is unlocked and ready to use. 
This change now not only checks for an allowance but now also checks if Alby is unlocked.
This means, if a website calls enable() and Alby is locked we now always show the prompt and ask the user to unlock.
If the user has an allowance already set the prompt will close after unlocking
otherwise the user will be asked to confirm the enable() call.
* Make sure to have an allowance on a website
* Lock Alby
* call webln.enable() - you should be prompted to unlock and the enable() promise resolves afterwards
> chore: add unlocked check to enable call

- src/app/components/form/TextField.tsx
Currently when hovering above an amount field, will already show stepper arrows because the label's take up all width.
- Removed making the label a block element (keeping it the default inline)
> refactor: input label should be inline

- src/app/components/AccountMenu/index.tsx
Fixes #859
I removed the connectors badge from the accounts dropdown menu.
Ran locally and verified that badges no longer appear in UI.
> refactor: remove connector badge from accounts dropdown

- playwright.config.ts
This tries to add a simple check to not accidentally run the end to end tests against the production app.
> chore: add check to not run tests against the production user API

- src/common/utils/signer.ts
Fixes #804
VerifyMessage will currently throw an error when using LNBits or LNDHub if a signature is incorrect. The actual behavior should be that it returns a Promise that shows if it was valid or not.
> fix: return if valid instead of throwing an error

- src/app/screens/Receive.tsx
- src/common/utils/helpers.ts
The receive screen makes API calls (maxAttempts: 20) to check if an invoice was paid. Currently there is no mechanism to abort those API calls when the receive screen gets closed (unmounted). This PR adds a shouldStopPolling option to the current poll implementation.
> feat: add function to abort polling

- babel.config.json
Get rid of distracting message when running jest tests in watch-mode:
```sh
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
```
> chore(jest): avoid babel loose warning

- src/extension/background-script/connectors/lnd.ts
Fixes #884
- New feature/bugfix (non-breaking change which adds functionality)
Currently we replace the path - assuming that the REST API runs on the root path.
This change now appends the LND API path
Tried to add a new account which was mentioned on twitter. 
Or: 
* add an LND account with a path
* check the background script console that the HTTP request is made to the correct URL with path: e.g. `/my/path/v1/getInfo`  (for this check you do not need to have an LND running on that path, the request will fail, but you see if the URL was as expected)
> Support paths on the LND URL

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Adjusted all templates:
- Use headlines instead of just bold to create automatic margin
- All entries have _descriptions_ to indicate what this means and that these can be removed
- Add further info
What do you think? Anything else we should add or improve?
> docs: align Github templates

- src/app/components/Container.tsx
Currently max-screen-width-${maxWidth} classes are ignored, because PurgeCSS doesn't handle dynamically created classes. (unless you explicitly define them in your tailwind setup).
This change makes sure that the classes are fully written and can be found by PurgeCSS
> fix: purgecss ignores max-screen classes

- src/app/screens/Home/index.tsx
- Currently the allowance menu sits empty on the right and doesn't indicate what it can do.
This change shows there is no budget "0 / 0" just like on the Publisher screen and gives you a hint what you could do with the menu.
Before:
After:
> feat: show it when there is no budget set

- src/extension/background-script/connectors/lndhub.ts
Fixes #961
Shows: "keysend not supported by the connected account." when not available. Instead of 404.
> fix: add descriptive message when method is not supported

- src/app/components/AccountMenu/index.test.tsx
- src/app/components/AccountMenu/index.tsx
- src/app/components/Menu/MenuItemButton.tsx
I have added a `selected` prop (as active is already in use because of Headless UI) to highlight the selected button in menu.
Do we have to update the stories to include the new selected prop? 
(`/src/app/components/Menu/Menu.stories.tsx`)
> feat: highlight selected account in menu

- src/app/screens/connectors/ConnectMyNode/index.tsx
- src/app/screens/connectors/ConnectStart9/index.tsx
- src/app/screens/connectors/ConnectUmbrel/index.tsx
This fixes the parsing of lndconnect URLs. Firefox recently made a change to comply with the specs (I could not find a changelog entry, but verified locally) of the `URL()` API, breaking Alby.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> fix: lndconnect workaround for Firefox

- src/extension/content-script/originData.ts
The icon seems more likely to be the logo. the image often is a full image to be shared on social media
> style: prefer website icon over image

- src/app/components/AccountMenu/index.test.tsx
- src/app/components/AccountMenu/index.tsx
- src/app/components/Menu/MenuItemButton.tsx
The selected state of accountmenu should just be part of that component, leaving the MenuItemButton a general component.
> fix: selected should only be part of accountmenu

- src/extension/content-script/index.js
Currently webln calls can be called multiple times and can lead to multiple prompts
This change checks that only one call at the time can be made. All parallel calls get ignored.
issue #601 
Open [boltz](https://boltz.exchange/)
> fix: prevent multiple parallel webln calls

- src/extension/content-script/index.js
This typo prevents extractLightningData() from being called.
> fix: request.type being used instead of request.action

- src/extension/background-script/db.ts
- src/extension/background-script/index.js
For some reason it seemed that the opening of the DB got blocked. This could be because of an error in adding the data from the extension storage.
Sadly it is not clear what can cause this.
I hope this change makes it a bit more resilient.
We have heard reports about errors that say "Could not establish connection. Receiving end does not exist."
It seems this is because the `db.open()` call never resolves (https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/index.js#L110) 
this means the message listeners are not added. 
It is not fully clear why`db.open()` does not resolve, but it seems there are issues with loading data from the extension storage into the IndexedDB. This PR optimizes loading the data. We now only add data when there is no …
> fix: refactor DB loading of allowances/payments

- src/app/screens/connectors/ConnectMyNode/index.tsx
- src/app/screens/connectors/ConnectStart9/index.tsx
- src/app/screens/connectors/ConnectUmbrel/index.tsx
- tests/e2e/createWallets.spec.ts
Use host instead of hostname to include the port number.
This prevents `GET https://umbrel.local/v1/getinfo net::ERR_CONNECTION_REFUSED` errors
> fix: url should include port number

- src/extension/content-script/originData.ts
This allows website owners to specifically set the title, description and image for Alby.
The following meta tags will be be preferred within Alby
- `alby:site_name`
- `alby:description`
- `alby:image`
> feat: special Alby meta tags

- src/app/components/AllowanceMenu/index.tsx
- src/app/screens/Accounts/index.tsx
We don't support screen readers so might as well turn off the`ariaHideApp` prop functionality of the react-modal which hides the background content from being accessed by screen readers when the modal is open.
--
- `chore`
--
Ran all tests
> chore: fix react-modal warning

- src/app/screens/Onboard/SetPassword/index.tsx
- src/app/screens/Unlock/index.tsx
- src/app/screens/connectors/ConnectCitadel/index.tsx
- src/app/screens/connectors/ConnectEclair/index.tsx
- src/app/screens/connectors/NewWallet/index.tsx
Follow up to #739. Uses endAdornment prop to add icon to view and hide password.
#679
<p>
</p>
Checked manually.
> feat: add view password using endAdornment

- src/app/screens/Publishers/index.test.tsx
- src/app/screens/Publishers/index.tsx
Allowances without budget should be listed but do not have an "active" badge
> fix: show allowances without budget

- src/extension/background-script/actions/allowances/__tests__/list.test.ts
- src/extension/background-script/actions/allowances/list.ts
- src/types.ts
we seem to still store payment amounts in strings.
This causes that numbers are concatenated instead of summed up.
> fix: handle stored payment amounts in strings

- src/app/screens/Settings.tsx
- src/common/constants.ts
- src/common/utils/currencyConvert.ts
- src/extension/background-script/state.ts
- src/types.ts
This add support to load the fiat exchange rates from the Alby server.
This means we no longer by default request data from third-party services (which has privacy implications for the user)
This is a manually tested additional settings option.
> Add support to load the exchange rate from the Alby server

- src/app/components/PaymentSummary.tsx
- src/app/router/Prompt/Prompt.tsx
- src/app/screens/ConfirmPayment/index.tsx
The initial configuration to render metadata in paymentsSummary Dialogue
1. structuring metadata on the client-side according to the schema.org specifications
2. extract metadata passed via sendPayment method
3.  return metadata in the payment response
4. add metadata to PaymentSummary to render it
```RouteParams```
```ConfirmPayment.tsx  -- ```
```props.metadata```
```
metadataRef
```
Tested by making payments with and without passing metadata from the client-side using prototype
> feat: intial configuration to render metadata in PaymentSummary

- src/extension/background-script/actions/accounts/__tests__/select.test.ts
- src/extension/background-script/actions/accounts/select.ts
- src/extension/background-script/actions/setup/reset.js
- src/extension/background-script/state.ts
we now manually call the saveToStorage() method whenever needed.
That means we should not need the complexity of these state subscriptions
> chore: removing state subscription to persist to browser storage

- src/app/components/ConnectorForm/index.tsx
- src/i18n/locales/en/translation.json
Updated the sats icon to the Alby logo on the onboard success screen.
https://github.com/getAlby/lightning-browser-extension/pull/1153#issuecomment-1186837656
Tested locally on light and dark modes.
> style: change sats icon to alby logo on onboard success screen

- src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
This PR fixes the wrong suggestion for Raspiblitz.
This has been tested with the latest Raspiblitz version v1.7.2.
> Fix url for raspiblitz v1.7.2

- .gitignore
- tests/e2e/createWallets.spec.ts
- tests/e2e/helpers/loadExtension.ts
- Use `userDataDir` pupeeteer option
- Reuse browser cache/storage/settings throughout test runs to avoid creating a new account to test functionality within the app
- chore/test
See e2e tests
> test: use puppeter user-data-dir option

- src/app/components/AccountMenu/index.tsx
- src/app/components/AllowanceMenu/index.test.tsx
- src/app/components/AllowanceMenu/index.tsx
- src/app/components/TransactionsTable/index.tsx
- src/app/components/form/DualCurrencyField/index.test.tsx
- src/app/components/form/DualCurrencyField/index.tsx
- src/app/context/AccountContext.tsx
- src/app/context/SettingsContext.tsx
- src/app/router/Options/Options.tsx
- src/app/router/Popup/Popup.tsx
- src/app/router/Prompt/Prompt.tsx
- src/app/router/Welcome/Welcome.tsx
- src/app/screens/ConfirmKeysend/index.tsx
- src/app/screens/ConfirmPayment/index.test.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/Home/index.tsx
- src/app/screens/LNURLPay.tsx
- src/app/screens/Publisher.tsx
- src/app/screens/Receive.tsx
- src/app/screens/Settings.tsx
- src/common/utils/__tests__/currencyConvert.test.ts
- src/common/utils/currencyConvert.ts
- src/extension/background-script/state.ts
- src/i18n/locales/en/translation.json
- src/types.ts
- tests/fixtures/settings.ts
This is the main integration of the new settings feature.
This PR does:
- add a new boolean to the DEFAULT_SETTINGs => `showFiat`
- `showFiat` is `true` by default
- ~Settings: If in development mode show a "Show Fiat" toggle~ => Toggle is shown in production
- Settings: If `showFiat` is `false` => hide settings for "currency"  and "exchange" 
- Add new SettingsContext and Provider which gets the current settings from `api.getSettings` 
- Wrap all screens with this Provider
- Settings: get settings now via SettingsContext and not directly from `api.getSettings` no more
- Settings: ensure to update the SettingsContext state too when saving new settings
- Acounts: Divide `getSats` and `getFiatValues`
- Acounts: get `showFiat`  from SettingsContext
- Accounts: do not fetch fiats if …
> feat(app): Show and convert fiats if setting is enabled

- src/common/lib/utils.ts
We don't know what's in the custom records anything can fail.
With invalid data the `atob` or the `JSON.parse` can fail.
We now just catch and ignore all errors here
> fix: catch boostagram parsing errors

- src/app/screens/LNURLPay.tsx
The new SettingsContext provides a hook `useSettings` which can be used on component level for reading the current settings.
closes https://github.com/getAlby/lightning-browser-extension/issues/1210
Added a userName and userEmail in Settings => input fields in LNURLPay screen are pre-filled
> refactor: use settings context in LNURLPay

- src/common/lib/lnurl.ts
Adjusting the output of this _error_.  
It's confusing because you can think that this is an actual error while this is just an info that's bech32 decoding did not work on this which is ok.
Code is doing this:
1. // maybe it's bech32 encoded?
2. // maybe it's a lightning address?
3. //maybe it's already a URL?
- chore
Before:
After:
> chore(lnurl): bech32 parsing eerror is just an info, not a real error

- src/extension/content-script/batteries/YouTubeVideo.ts
This query selector no longer seems to be unique and now matches
two elements. To fix it we simply use the textcontent of all matching elements.
Send some sats to: https://www.youtube.com/watch?v=-WAZ2UCabZs
> fix: youtube battery

- .github/workflows/build.yml
- README.md
We now use nightly.link to link to the build files and because of that no longer need S3. 
This seems to be much easier as we do not need to upload the files to S3 and this also means the workflow does no longer need any sensitive data and thus we can comment the build link on all PRs
Additionally this also uses the production getalby.com accounts
> chore: update build workflow

- src/app/components/PaymentSummary.tsx
- src/app/router/Prompt/Prompt.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/schema/metadataValidator.ts
change metadata type to string
change rendering mechasim by parsing stringified change and rendering it as javascript object
pass it as as string will help it to store metadata as JSON in db
> feat: change metadata type to string

- src/app/components/TransactionsTable/index.test.tsx
- src/app/components/TransactionsTable/index.tsx
the message is a random string provided by the user
> fix: remove decodeURI from boostagram message

- src/extension/content-script/batteries/Twitter.ts
1) Fixes header font size
2) We've been using `document.title` in Twitter batteries, but that would also show the notifications, disturbing the design of the screen. This replaces it with the user's name from the h2 tag.
https://github.com/getAlby/lightning-browser-extension/pull/1118#issuecomment-1205429623
cc @dvoroneca 
Tested Manually.
> Task revamp issues

- src/extension/background-script/db.ts
- src/extension/background-script/events/persistMetadata.ts
- src/types.ts
transaction metadata can be used for describing free transactions and well as commercial transactions (providing bought content in form of metadata)
add contentUrl field to be stored as an optional field in a separate column
Use case division
user can use transaction metadata spec, to give details about the transaction along with commercial purpose i.e give some content to the user after successful payment
1.  Metadata just describes the transaction, no confidential information is shared which shall be protected before payment
a> don't provide ```contentUrl```  in transaction metadata (as contentUrl field is optional) 
transactions which are free, and don't give any content in return eg. donations
b> provide ```contentUrl``` in transaction metadata (even if it's not confidential render it …
> proposal: use contentUrl field to trigger after actions on wallet side

- src/app/router/Options/Options.tsx
- src/app/router/Popup/Popup.tsx
- src/app/router/Prompt/Prompt.tsx
- src/common/lib/utils.ts
As discussed below:
The problem of the [bug ticket](https://github.com/getAlby/lightning-browser-extension/issues/1286) is not that the Toast Messages of an Invalid Password should surpressed if the screen is not Unlock (because Unlock screen has its own error rendering).
Instead, the problem is that the Screen Unlock is not aware of Toasts at all. 
This has to be changed and toasts should appear on this screen too.
Closes https://github.com/getAlby/lightning-browser-extension/issues/1286
- Feature
> feat(unlock): render Toasts on Errors

- src/extension/background-script/index.ts
When a user uninstalls Alby they will now be directed to this URL: https://form.jotform.com/221745756722057
#210 
Uninstalled the app and was taken to the feedback form.
> feat: add feedback form on uninstall

- src/app/screens/Send/index.test.tsx
- src/i18n/locales/en/translation.json
Small label update to indicate the user can enter a LNURL or a lightning address
first quick minor improvement for #1303
> chore: indicate a user can pay a ln address or add a LNURL string

- src/app/router/Prompt/Prompt.tsx
- src/app/screens/ConfirmPayment/index.test.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/Send/index.tsx
A follow up refactoring for Confirm Payment:
- use navState for receiving origin and paymentRequest data
- remove useRef from storing data which is already existent
Follow-Up on PR https://github.com/getAlby/lightning-browser-extension/pull/1264
Making payments on Stackernews
> refactor: use navstate for confirm payment

- src/app/screens/LNURLAuth/index.tsx
- src/app/screens/LNURLPay/index.tsx
- src/app/screens/LNURLWithdraw/index.tsx
Align close actions for all actions. Those will not be reached by the modal because it is closing itself on success.
#1216 
- `refactor`
Manually tested with fiatjef and starblocks
> fix(lnurlpay): correct close for popup/prompt

- src/app/components/PaymentSummary.tsx
- src/app/components/PaymentSummary/index.test.tsx
- src/app/components/PaymentSummary/index.tsx
- src/app/screens/ConfirmKeysend/index.tsx
- src/app/screens/ConfirmPayment/index.tsx
This PR renders the Fiat Amount of a confirmable payment (if the setting "showFiat" is true and fiatAmount exists accordingly).
~Design came from https://github.com/getAlby/lightning-browser-extension/issues/1306#issuecomment-1222261734~
=> Design changed, see Screenshot and comments below
Closes https://github.com/getAlby/lightning-browser-extension/issues/1306
usign Stackernews and invoke payments
> feat: show fiat in Confirm Payment

- src/extension/inpage-script/index.js
All WebLN interactions are using `window`. Let's also expose the ready event on the window object for consistency (it automatically bubbles to the document so this change is fully backwards-compatible)
> fix: expose ready event on window

- src/app/components/ConnectorForm/index.tsx
- src/app/screens/connectors/ConnectCitadel/index.tsx
- src/app/screens/connectors/ConnectEclair/index.tsx
- src/app/screens/connectors/ConnectGaloy/index.tsx
- src/app/screens/connectors/ConnectLnbits/index.tsx
- src/app/screens/connectors/ConnectMyNode/index.tsx
- src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
- src/app/screens/connectors/ConnectStart9/index.tsx
- src/app/screens/connectors/ConnectUmbrel/index.tsx
- tests/e2e/createWallets.spec.ts
Pull request for issue #1151 
This will add a hyperlink to the titles of the different Wallet Connectors. I haven't manage to add them at all connectors (such as BTCPay) because they get their title from the translation file and I couldn't figure out how to do it effectively yet.
> adding website-links to connectors

- src/app/screens/Home/index.tsx
This PR fixes these issues:
- loadPayment was running twice on Home because the dependency `allowance`  changed too late
- All Payments were shown, because loadPayments was running too fast and loaded all payments from DB
The fix is to wait until `loadAllowance` is done and then trigger `loadPayments`.
**Please test again ! 🙏** 
We agreed on refactoring the whole HOME screen, which will follow in another PR. See ticket https://github.com/getAlby/lightning-browser-extension/issues/1359
Resolves https://github.com/getAlby/lightning-browser-extension/issues/1350
- Manually with doing payments on https://stacker.news and https://insatgram.getalby.com/
- Then open the extension on both websites again to check that the correct payments …
> fix(home): wait for allowance before loading payments

- src/app/components/ConnectorForm/index.tsx
- src/app/screens/Home/index.tsx
- src/app/screens/LNURLAuth/index.tsx
- src/app/screens/Send/index.tsx
- src/app/screens/connectors/ConnectCitadel/index.tsx
- src/app/screens/connectors/ConnectEclair/index.tsx
- src/app/screens/connectors/ConnectGaloy/index.tsx
- src/app/screens/connectors/ConnectLnbits/index.tsx
- src/app/screens/connectors/ConnectMyNode/index.tsx
- src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
- src/app/screens/connectors/ConnectStart9/index.tsx
- src/app/screens/connectors/ConnectUmbrel/index.tsx
- src/extension/background-script/actions/lnurl/auth.ts
- src/extension/background-script/events/__test__/notifications.test.ts
- src/extension/background-script/events/notifications.ts
- src/extension/inpage-script/index.js
- src/types.ts
- tests/e2e/createWallets.spec.ts
- tests/e2e/walletFeatures.spec.ts
- Handle empty origin for auth-notifications
#770
- Login via `Send` without `Origin`
- Login via `Prompt` with `Origin`
Manually and added a basic unit-test
> Fix/770 show relevant/correct auth-data in auth-notfications

- src/app/components/Container.tsx
- src/app/screens/ConfirmKeysend/index.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/ConfirmSignMessage/index.tsx
- src/app/screens/Enable/index.tsx
- src/app/screens/LNURLAuth/index.tsx
- src/app/screens/LNURLChannel/index.tsx
- src/app/screens/LNURLWithdraw/index.tsx
- src/app/screens/MakeInvoice.tsx
Fixes success message positioning.
https://github.com/getAlby/lightning-browser-extension/pull/1330#discussion_r953850033: Also has been tested in other places as requested!
~ #1330
> fix: success message positioning

- src/extension/content-script/batteries/Monetization.ts
- src/extension/content-script/originData.ts
this make the check for the lightning metatag case in-sensitive. 
Checks for `name="alby:name"` and "alby:description" metatags to load the website information.
currently we only checked for `property="alby:name"` this feels a bit inconsistent because for the lightning meta tage we use the `name` attribute.
> case insensitive monetization and more consistent alby metatags

- src/app/components/TransactionsTable/index.tsx
- src/app/screens/Home/index.tsx
- src/common/lib/api.ts
- src/extension/background-script/actions/ln/invoices.ts
Payments have `memo` instead of description.
We currently use this as title for a (payment-)transaction. But titles get cut-off if they are too long, see screenshot.
With this we make sure the full description can always be checked.
Also
- updated type
- renamed some code to make it easier to understand
Manually
> feat(transactiontable): show payment memo as description

- src/extension/inpage-script/index.js
Capture ALL `lightning:` links.
#1307 
> Capture links in dynamic content

- src/app/components/AccountMenu/index.tsx
- src/app/components/AllowanceMenu/index.tsx
- src/app/screens/Home/index.tsx
- src/app/screens/Onboard/SetPassword/index.tsx
- src/app/screens/Publisher.tsx
- src/app/screens/Publishers/index.tsx
- src/common/lib/utils.ts
Removes the toast from being called in the utils function itself as in some places we again check if there's an error and add a _second_ toast.
#1333
Manually
> fix: remove error toast from utils.call

- src/app/components/PublisherCard/index.tsx
- src/app/screens/LNURLPay/index.tsx
Removes the default image whenever there isn't one.
[It still shows up when there's an error in loading the image, though]
#1379 
<p>
</p>
Manually
> fix: remove default image in publisher card

- src/extension/content-script/batteries/LinkTree.ts
Adds space after description so that the lightning address if in end of description doesn't get appended like this:
`hello@getalby.comLightning Buzz for yo...`
> fix: add space after description

- src/app/screens/Settings.tsx
- src/common/lib/utils.ts
- src/extension/background-script/state.ts
- src/i18n/locales/en/translation.json
- src/types.ts
Adds an option to enable/disable browser notifs globally
Closes #1367
https://user-images.githubusercontent.com/64399555/190345484-026da224-9bc8-49b1-9d97-d618d9b22fe1.mp4
Using send and receive as in above video
> feat(settings): enable/disable browser notifications

- src/extension/content-script/batteries/helpers.ts
Makes [.] after @ mandatory as it can confuse for links with @ in between
For example:
`⚡️ https://tippin.me/@njelsalvador` is a valid ln address as per the old regex as it has `⚡️ + words + @ + words`
Changed it to:
`⚡️ + words + @ + words + .(dot) + words`
Fixes #1437 
https://www.youtube.com/watch?v=PqNRpStZRAE
> fix: ln address regex

- .github/workflows/unit-tests.yml
This is adding a coverage report to the Github action summary.
Can be useful to check coverage without running it locally. And this does not add spamy comments to a PR.
Looks like this:
> ci: add coverage as github action summary

- src/extension/background-script/connectors/citadel.ts
- src/extension/background-script/connectors/connector.interface.ts
- src/extension/background-script/connectors/eclair.ts
- src/extension/background-script/connectors/lnbits.ts
- src/extension/background-script/connectors/lndhub.ts
Aligns the SignMessageResponse to send message back every time
Closes #1405
Tested using LND and LNDHub accounts
> fix: align signmessage response in all connectors

- src/app/context/SettingsContext.tsx
- src/app/screens/Settings.tsx
When changing currency in settings the fiat-rate in the account-menu is not being updated
- make sure fiat-rate is being renewed when changing currency in settings (re-add dependency to effect)
- remove `fetachAccountInfo` call because it's not needed anymore
Manually
> fix(settings): make sure new fiat-rate is being used on currency switch

- src/app/components/TransactionsTable/index.tsx
Fix the vertical position of the **arrow toggler** on the right if no title exists and the option "Sats to Fiat" is disabled.
_Wrong position_
_Fixed position_
No tests needed.
> fix: adjust transaction toggle (vertical) position

- src/app/components/form/DualCurrencyField/index.tsx
I have added a "wheel" event listener on input and on callback of the event just preventing the fired event.
Fixes #1593 
(Remove other not matching types)
I opened up the extension in Chrom and after login went to Receive tab, In amount-input entered some numbers and tried to scroll up & down to change the value, but it not changing.
> fix: amount-input changes value on scroll

- src/app/screens/Publishers/websites.json
I added the new website [BTC Map](https://btcmap.org) to the Websites directory under the Shopping category. BTC Map has just launched a lightning tipping feature for map contributors and there will be more lightning integration in the future that will be compatible with Alby users.
I noticed that for the other logo assets on this page you are using an Alby CDN to serve the images. I have included a URL to the BTC Map logo which can be left as-is or can be downloaded and added to the asset server with the others.
Thanks!! 🙂 
I ran this locally.
> feat: add btcmap to the website directory

- src/app/components/Setting/index.tsx
_In the settings tab, when opting for Portuguese Brasil, LNURL-Auth antigo subtitle is very close to the toggle button._
Change language to Portuguese Brasil on settings
Fixes _#1596_
**Updated Image**
**Old Image**
_✅ Unit Tests_
> fix: close text to switch (settings) #1596

- src/app/screens/Settings.tsx
- src/i18n/locales/en/translation.json
__LNURL_Auth's hint text in the settings tab is displayed with HTML tags. They need to be parsed so that hint text is shown as expected with relevant break and strong tags_
Fixes _#1597_
#**Updated Image**
#**Old Image**
_✅ Unit tests_
> fix: text displayed with tags #1597

- src/app/screens/LNURLAuth/index.tsx
- src/i18n/locales/en/translation.json
Align the success screen of LNURLAuth
#1379
Manually
> feat: use resultcard in lnurlauth

- src/app/screens/ConfirmPayment/index.test.tsx
- src/app/screens/ConfirmPayment/index.tsx
_Remove "Remember and set a budget" option from send screen when opting for lightning invoice_
_Fixes #1510_
- _Previous behaviour_ 
- _After removal of "Remember and set a budget"_
_Manual Testing_
- I used ln invoice from Phoenix and tapped Send on popup and website, which shows "Remember and set a budget" but with the changes it has been removed
- Lightning invoice used:  lnbc1m1p3ngewjpp578s6uh2gvmsuldc7khppc57spggzjuy9aj0cg4633put5x20p6cqdqqxqyjw5q9q7sqqqqqqqqqqqqqqqqqqqqqqqqq9qsqsp5e5a6h39y85fnvlenly6dmfx97y32tru4hkn84x0wcgjf8egyfk4qrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glclll0mxh6jgh2xuqqqqlgqqqqqeqqjqfs7gjqntggjnpgxp9rjh78gx2cczjuha65wdz9w2462chm8a7d78s2gwpdndsra4lf7940dh03dw67xcr8dd605lm68j6pusjj7n9tspm0mtde …
> fix: remove Remember & set budget from send #1510

- src/app/components/AllowanceMenu/index.test.tsx
- src/app/components/AllowanceMenu/index.tsx
- src/app/screens/LNURLPay/index.test.tsx
- src/app/screens/LNURLPay/index.tsx
A quick fix for the test warnings (e.g. [here](https://github.com/getAlby/lightning-browser-extension/actions/runs/3219301525)):
- properly mock `getFiatValue`
- fix: initial value for "budget" in component AllowanceMenu
- fix: call `getFiatValue` only if sat value is defined
- test how many times `getFiatValue` was called
**Test run:** The warnings are gone => https://github.com/getAlby/lightning-browser-extension/actions/runs/3220138671
Simply by running yarn test:unit only.
> refactor: remove act warnings for allowance-menu & lnurl-pay

- src/app/components/AccountMenu/index.tsx
This change is about the account title. Replace JS cutting by a CSS solution. The full account title is displayed on mouse over (`title` attribute).
Fixes #1567
**Short title**
**Long title**
**Long title mouse over**
`yarn run dev:chrome`
> fix: truncate account title

- src/app/components/ConfirmOrCancel/index.tsx
- src/app/components/SatButtons/index.tsx
- src/app/screens/LNURLPay/index.tsx
_On tapping Confirm, while loading **Amount, Comment, Name, Email, Buttons, Cancel button** should be disabled_
Fixes _#1572_
On tapping Confirm all these options get disabled as they should be, as details have already been specified.
_Open [this ](https://www.youtube.com/c/KoreacomK) on your browser, tap on getAlby extension, click Send Satoshis, now on the next window after adding Amount, Comment, Name, and Email, and click on Confirm all these fields should be disabled. It's working as it should be as specified in issue._
> fix(lnurlpay): disable input fields buttons #1572

- src/app/screens/Send/index.test.tsx
- src/app/screens/Send/index.tsx
- src/i18n/locales/en/translation.json
_Fixed Send UX: Too long input placeholder is being cut off
On tapping Send UX, the input field is having placeholder which is cut off in Portuguese. So added hint text and updated placeholder text_
Fixes _#1517_
_Checkout below comments_
_Tests are passing locally, final image attached below_
> fix: input placeholder got cut (send) #1517

- src/extension/background-script/connectors/lnd.ts
- src/extension/background-script/connectors/lndhub.ts
Add reverse to incoming payments to correct wrong order
Fixes #1625
Manually with a bluewallet account
> fix(connectors): lndhub incoming tx order #1625

- src/extension/background-script/connectors/lnbits.ts
lnbits `payments` api shows outgoing and incoming payments. Negative ones are outgoing and need to be filtered out for our incoming txs.
Fixes #1631
Manually by sendign sats back and forth
> fix(connectors): lnbits incoming payments shows outgoing ones as well

- src/app/components/AllowanceMenu/index.test.tsx
- src/app/components/AllowanceMenu/index.tsx
- src/app/context/AccountContext.tsx
- src/app/context/SettingsContext.tsx
- src/app/screens/ConfirmKeysend/index.test.tsx
- src/app/screens/ConfirmKeysend/index.tsx
- src/app/screens/ConfirmPayment/index.test.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/Home/index.tsx
- src/app/screens/LNURLPay/index.test.tsx
- src/app/screens/LNURLPay/index.tsx
- src/app/screens/LNURLWithdraw/index.test.tsx
- src/app/screens/LNURLWithdraw/index.tsx
- src/app/screens/Publisher.tsx
- src/app/screens/Receive/index.tsx
- src/common/utils/__tests__/currencyConvert.test.ts
- src/common/utils/currencyConvert.ts
- src/extension/background-script/events/notifications.ts
During the refactor I didn't notice that this was redundent and doesn't need to be async anymore.
- refactor
Manually
> refactor: remove redundent code

- src/app/components/Button/index.tsx
- src/app/components/ConfirmOrCancel/index.tsx
Focus CTA in prompt to make confirmation faster.  
Especially for usecases like nostr-chats where you need to confirm multiple times.
Manually
> feat(confirmorcancel): focus the submit button

- src/app/components/ConfirmOrCancel/index.tsx
- src/app/screens/LNURLPay/index.tsx
Avoid setting focus for LNURLPay screen so it's not being cut-off
Manually
> fix(lnurlpay): avoid send-start screen being cut-off by focusing #1641

- src/app/components/AllowanceMenu/index.test.tsx
- src/app/components/AllowanceMenu/index.tsx
- src/app/context/AccountContext.tsx
- src/app/context/SettingsContext.tsx
- src/app/screens/ConfirmKeysend/index.test.tsx
- src/app/screens/ConfirmKeysend/index.tsx
- src/app/screens/ConfirmPayment/index.test.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/Home/index.tsx
- src/app/screens/LNURLPay/index.test.tsx
- src/app/screens/LNURLPay/index.tsx
- src/app/screens/LNURLWithdraw/index.tsx
- src/app/screens/Publisher.tsx
- src/app/screens/Receive/index.tsx
This is a refactoring which resulted from out the discussion in PR https://github.com/getAlby/lightning-browser-extension/pull/1614
- store latest currency rate in SettingContext ref instead of state to prevent a re-render
- when `getFiatValue` is called => always check if the currency in the state matches with the currency in the ref, and update otherwise
- => this ensures that the fiat value is calculated with the correct rate
- => this ensures that the latest currency rate is called from the background script only once when the currency changed 
- Also wrap `getFiatValue` in a try/catch block and display an error when a sat to fiat conversion failed
Unfortunately this reverted a few commits from [this PR](https://github.com/getAlby/lightning-browser-extension/pull/1643/files) again …
> refactor: store currency rate in settings ref

- src/extension/content-script/onend.js
- src/extension/inpage-script/webln.js
- src/extension/ln/webbtc/index.ts
- src/extension/webbtc/index.ts
Adds a new `WebBTCProvider`
Fixes #1081 
https://user-images.githubusercontent.com/64399555/193761552-b6eaae48-f535-4073-9043-64528b5152a4.mp4
> feat: implement webbtc

- src/common/lib/lnurl.ts
Mainly trying to avoid `let lnurlDetails = {} as LNURLDetails;` and be more explicit about types. So instead of forcing the type we let TS figure it out by defining possible types in other places.
> refactor(lnurl): getDetails - avoid typecasting

- src/app/screens/Receive/index.tsx
_In Recieve tab, on tapping Create Invoice while loading Amount, & Description fields should be disabled. _
Fixes #1659 
_Go to receive tab, and mention Amount and Description. On clicking Create Invoice while loading input fields are disabled as it should be. Previously it can be edited while loading._
> fix: disable input fields on Create Invoice #1659

- src/app/router/Prompt/Prompt.tsx
- src/app/screens/Nostr/ConfirmSignMessage.tsx
- src/extension/background-script/actions/nostr/signEventOrPrompt.ts
- src/extension/background-script/nostr/index.ts
- src/extension/ln/nostr/types.ts
- src/types.ts
The [spec NIP07](https://github.com/nostr-protocol/nips/blob/master/07.md) says the full event with signature must be returned. So far we had only returned the signature.
We now also have a special ConfirmSignMessage screen for nostr events because the default ConfirmMessage screen still has some signing specific code which we don't need and want for nostr.
fixes #1687
> fix(nostr): return fully signed nostr event

- src/app/screens/Accounts/index.tsx
Highlights the menu button using a border
Fixes #1656
Normal:
Normal (On hover):
Dark:
Dark (On hover):
Manually
> fix: highlight menu icon dots

- jest.config.js
- package.json
- yarn.lock
Removes the citadel npm package
Step 2: #1314 
- `chore`
> chore: remove unused runcitadel sdk

- src/extension/content-script/batteries/GitHub.ts
Handles both org pages and profile pages separately.
Fixes #1709
1) Org Page 2. Profile Page
<p>
</p>
Tested manually in @dipien and @im-adithya
> feat: handle organization pages

- src/extension/content-script/batteries/Reddit.ts
We've been fetching the description from meta description tag but that's gets cut when it exceeds a character limit thereby not showing the ln address in the description which is in the ending... Hence it works in https://www.reddit.com/user/derbumi but not in https://www.reddit.com/user/maxirosson
Fixes #1710
Manually here: https://www.reddit.com/user/maxirosson
> fix: fetch from description element

- src/app/screens/Home/DefaultView/index.tsx
- src/extension/background-script/actions/ln/invoices.ts
- src/extension/background-script/connectors/citadel.ts
- src/extension/background-script/connectors/connector.interface.ts
- src/extension/background-script/connectors/eclair.ts
- src/extension/background-script/connectors/galoy.ts
- src/extension/background-script/connectors/lnbits.ts
- src/extension/background-script/connectors/lnd.ts
- src/extension/background-script/connectors/lndhub.ts
We throw an error on the error case
fixes #1712 
needs testing
> chore: unify connector functions

- src/app/components/TransactionsTable/index.test.tsx
- src/app/components/TransactionsTable/index.tsx
* no need to display the type if all transactions are the same
* preimage is not that important move it lower
* properly show fees
issue: #1662
> chore: slightly try to cleanup the transaction list

- src/extension/inpage-script/index.js
so far we only looked for `lightning` query params and missed `LIGHTNING`
test on: https://donate.pavlenex.com/
> fix: case insensitive bitcoin links

- package.json
- webpack.config.js
- yarn.lock
the bundle analyzer writes a stats file on each build. This should help us to understand the size of the package better
Fixes #1750
> chore: add webpack bundle analyzer to keep an eye on the bundle size

- package.json
- yarn.lock
> Latest [wext-manifest-loader](https://github.com/abhijithvijayan/wext-manifest-loader) needs node v16.15.0 as a minimum.
Now that we support all node versions, we can update this too!
~⚠️ This PR changes our minimum supported version to v16 from v14~
~[Hence waiting on #1714 for failing tests]~
- `chore`
> Update manifest loader

- src/app/screens/LNURLPay/index.tsx
Breaks text instead of overflowing in lnurlpay screen.
[I wonder why we aren't using Content Message here (similar to Keysend) like this:]
❌ Not the actual change
Fixes #1786
✅ Actual Change
> fix(lnurlpay): description overflow

- src/app/components/PublisherCard/index.tsx
Long website names / titles currently allow the publisher card to grow indefinitely: (and shift important UI elements out of the view at the bottom)
> fix: overflow of website title

- src/extension/background-script/actions/nostr/decryptOrPrompt.ts
- src/extension/background-script/actions/nostr/encryptOrPrompt.ts
- src/extension/background-script/actions/nostr/index.ts
- src/extension/background-script/nostr/__test__/nostr.test.ts
- src/extension/background-script/nostr/index.ts
- src/extension/background-script/router.ts
- src/extension/content-script/onendnostr.js
- src/extension/ln/nostr/index.ts
- src/types.ts
Implement NIP04: `encrypt` & `decrypt`
#1730 
> feat: implemented nip04

- src/app/screens/Send/index.tsx
when scanning a QR code for an invoice there might still be the "lightning:" protocol in the text.
this change removes this.
> feat(qr scanner): remove potential lightning: protocol

- src/app/screens/Enable/index.tsx
- src/app/screens/Home/DefaultView/index.tsx
- src/app/screens/Nostr/Confirm.tsx
- src/app/screens/Nostr/ConfirmGetPublicKey.tsx
- src/extension/content-script/onend.js
- src/extension/content-script/onendnostr.js
- src/i18n/locales/en/translation.json
the blocklist only takes effect after a page reload.
This might be confusing for the user as the user adds something to the blocklist but it has no effect (until a page reload)
This alert is a quick hack to give the user some feedback.
This PR also adds a check to ignore any webln/nostr calls from the website if the enable call has failed. This prevents the website from spamming the user with multiple prompts.
> feat: added blocklist note

- src/app/screens/ConfirmKeysend/index.tsx
- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/ConfirmRequestPermission/index.tsx
- src/app/screens/Keysend/index.tsx
- src/app/screens/MakeInvoice/index.tsx
- src/app/screens/Nostr/Confirm.tsx
- src/app/screens/Nostr/ConfirmGetPublicKey.tsx
- src/app/screens/Nostr/ConfirmSignMessage.tsx
_Wrapped all the ConfirmorCancel components forms with forms and handling submit operation via onSubmit instead of onClick_
Fixes _#1617_
_Refactored code_
> refactor: form el for ConfirmorCancel #1617

- src/app/components/CompanionDownloadInfo.tsx
+ From MDN:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/appVersion
> Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. ... Be aware that this feature may cease to work at any time.
There's no such warning for `userAgent` and here's a source on how to use it instead:
https://www.educative.io/answers/how-to-detect-the-operating-system-of-the-client-machine-using-js
+ only on my local system. Trusting the linked blog post that user agents are generally well-behaving and as reliable as `appVersion`.
> refactor: getOS: don't use deprecated appVersion.

- static/views/options.html
- static/views/welcome.html
Favicons in extension pages
--
Manually
> fix: add favicon to extension pages (firefox)

- src/app/components/Navbar/Navbar.tsx
+ https://github.com/getAlby/getalby.com/pull/272
+ [x] review code
+ [x] depending on responsiveness needs, consider moving the navigation entries ("websites" etc.) a bit more to the right so they are more centered instead of leaning left.
+ [x] reviewer: test with an extension development setup (or pair with me / let me know how to set one up)
+ [x] reviewer: test responsiveness (current extension's header looks as broken to me on smaller breakpoints as with these changes but I'm not sure!?)
+ Navbar: constrain max width to same width as the content.
+ reason: on desktop the navigation items in the top left and right corners were easy to miss. With this change, everything is closer together and easier to notice.
+ UI improvement
+ ~~⚠️ I only tested this with my browser's inspector. I …
> refactor: Navbar: constrain max width to same width as the content.

- src/extension/background-script/actions/lnurl/__tests__/auth.test.ts
- src/extension/background-script/actions/lnurl/auth.ts
- tests/fixtures/msw/handlers.ts
When the result returned by the lnurl auth api is missing a field, the prompt should be Auth: Something went wrong
- Fixes #1874
For example, the status field is missing
after fix 
> fix: lnurl auth return value cause  error msg

- src/common/lib/utils.ts
- src/common/utils/window.ts
This makes sure that the prompt is focussed every 2 seconds. 
If the user "looses" the prompt this change brings the prompt in focus again.
Fixes #1856
https://share.cleanshot.com/ZmEgc6
> feat: always focus prompt

- src/extension/background-script/actions/allowances/__tests__/enable.test.ts
Edit the allowance enable test  fixture data
When checking the data, the data with id 2 is used, so there can only be one item fixture data
```
const allowance = await db.allowances.get(2);
```
> fix: allowances enable unit test fixture data

- src/app/screens/Send/index.tsx
Adds support for BIP21 invoices in Send Screen
Fixes #1897 
<p>
<p/>
Using this BIP21 invoice: `bitcoin:bc1q0gf7ygdcwjxtfgmzlaqqtxn3s7sdamyw5v48a5?label=Buy%20me%20Coffee&message=Let%27s%20test%20BIP21&amount=0.0005&lightning=lnbc10u1p3pj257pp5yztkwjcz5ftl5laxkav23zmzekaw37zk6kmv80pk4xaev5qhtz7qdpdwd3xger9wd5kwm36yprx7u3qd36kucmgyp282etnv3shjcqzpgxqyz5vqsp5usyc4lk9chsfp53kvcnvq456ganh60d89reykdngsmtj6yw3nhvq9qyyssqjcewm5cjwz4a6rfjx77c490yced6pemk0upkxhy89cmm7sct66k8gneanwykzgdrwrfje69h9u5u0w57rrcsysas7gadwmzxc8c6t0spjazup6`
> feat: support bip21 invoices in send

- src/app/screens/Publisher.tsx
Currently the website url is displayed twice. Instead we want to show the website name as the title of the publisher card.
> fix: display name instead of url as the publishercard title

- src/common/lib/utils.ts
Normally when we open a new window the prompt is the only tab in this window If that's the case we have to close the prompt using windows.remove()
Some browsers force the new window to open in a tab. In this case we have to close the prompt using tabs.remove()
Some browsers actually can close the window when tabs.remove() removes the only/last tab. But Opera fails with the following error: "Tabs cannot be edited right now (user may be dragging a tab)"
> fix: remove window or tab based on what the browser opens

- src/extension/background-script/index.ts
Whenever we remove the extension and load it again, the state is persisted, but the user is redirected to welcome page to set a new password. But we can still unlock the extension using the last used password before removing the extension.
https://user-images.githubusercontent.com/64399555/214838447-dabe7d82-2e7b-4cc2-9cfd-3705240b827d.mov
https://user-images.githubusercontent.com/64399555/214838660-307d3253-e88e-4600-a078-75aa7f07809a.mov
Tested manually.
> fix: avoid showing welcome screen on re-install

- package.json
- src/extension/background-script/db.ts
- src/extension/background-script/index.ts
- yarn.lock
TLDR; Uses fake-indexeddb to make Alby work in Tor
`indexedDB.open()` throws errors in Firefox Private Mode. You might not be reproduce this in Firefox by enabling Private Mode access to the extension because it still initializes using the default mode's indexedDB (and hence also reflects the changes made in Private Mode to normal mode as well). However, in browsers like Tor, the only available mode (during initialization of the extension) is Private Mode so that makes `indexedDB.open()` throw an error.
To tackle this, we use fake-indexeddb whenever we detect this error thrown due to lack of indexedDB. (We conditionally initialize Dexie with `IDBKeyRange`and `indexedDB` from fake-indexedDB from `._options` and `._deps`)
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=781982
- …
> chore: use fake (in memory) indexed db if indexedDB is not available (Tor Browser)

- package.json
- src/app/components/AccountMenu/index.tsx
- src/app/screens/Accounts/index.tsx
- yarn.lock
As described in the issue the changes add an Identicon avatar icon to the accounts menu. See screenshots for more infos.
This is the same change as https://github.com/getAlby/lightning-browser-extension/pull/1990 but with the https://avvvatars.com/ lib. https://github.com/nusu/avvvatars 
This lib has types, but the styles are also different. Two styles are available: character and shapes (see screenshots) I personally prefer "character".
Fixes [_#1987_](https://github.com/getAlby/lightning-browser-extension/issues/1987)
Tested manually by running extension.
> feat: add account menu avatars - avvvatars lib

- src/app/screens/Discover/websites.json
I added https://channel.ninja to the discover websites.
For the logo I used my self hosted logo, this needs to be changed out for one hosted on cdn.getalby-assets.com.
Adding one object to the websites array shouldn't break anything. so no tests for this 🤞
> feat: add channel.ninja to discover websites

- src/app/screens/Discover/websites.json
+ fixes https://github.com/getAlby/lightning-browser-extension/issues/2018
+ adds [Hamstr](https://hamstr.to/) to list of Nostr clients.
+ reduces total file size from `2.4MB` to `179kB`.
+ Compressed images will be uploaded to DigitalOcean (DO) bucket. File extension were changed from `.svg` to `.png` because those were either:
a. fake SVGs that only contained embedded PNGs (I extracted the PNG content, so it's a real PNG now - no worries).
b. real SVG files I found on the net did not fit square formatting or had weird viewbox/size parameters so I couldn't get them to fit into our page without editing the SVGs in Adobe Illustrator -> converted to PNG with photoshop
+ PNGs were scaled to 256x256px where the original PNG was large enough. One original image was slightly smaller and I kept …
> Compress discover page images

- README.md
In the Contributing section there's a link for good first issues for developers. Thats broken because there's also a design label in it. I took out the design label.
Clicked on the fixed link in the README and it shows the correct issues.
> fixed 'good-first-issue' link in README

- src/app/components/Navbar/Navbar.tsx
Removes duplicate spacing on lg screens. (container already has `px-4`)
> fix: spacing on lg

- src/app/components/AllowanceMenu/index.tsx
The modal doesn't open because the totalBudget is set to null and we are using `.toString()` method on it.
Fixes #2078
Tested manually
> fix: total budget is set to null

- src/extension/background-script/actions/settings/changePassword.ts
Fixed update password error when `nostrPrivateKey` is null, so that the code doesn't crash.
Fixes #2075 
https://user-images.githubusercontent.com/74018438/217173649-acf57eba-a03d-4470-a17d-bb8d58b61a38.mp4
> fix: update password bug when nostrprivatekey is null

- src/app/context/SettingsContext.tsx
- src/common/constants.ts
- src/extension/background-script/state.ts
- tests/fixtures/settings.ts
This reduces the size of the extension greatly as this removes the dependency on background-script in settings provider used in welcome, options, popup, and prompt routes.
Fixes #2089
- `chore`
> chore: move default_settings to constants

- src/app/screens/Accounts/Show/index.tsx
- src/i18n/locales/en/translation.json
Adds try catch in the useEffect hook (used when the migrated nostr key is malformed in the first-place)
Manually
> fix: show toast if nostr key is malformed

- src/app/components/TransactionsTable/index.tsx
The preimage is now showing in transaction table as somehow it had previously been removed. I have added a check to see if there is indeed a preimage present or not.
Fixes #2105 
> fix: preimage in transaction table

- src/app/router/Prompt/Prompt.tsx
- src/app/screens/Nostr/ConfirmSignSchnorr.tsx
- src/extension/background-script/actions/nostr/__tests__/signSchnorr.test.ts
- src/extension/background-script/actions/nostr/helpers.ts
- src/extension/background-script/actions/nostr/index.ts
- src/extension/background-script/actions/nostr/signSchnorrOrPrompt.ts
- src/extension/background-script/nostr/index.ts
- src/extension/background-script/router.ts
- src/extension/content-script/onendnostr.js
- src/extension/ln/nostr/index.ts
- src/types.ts
Adds signSchnorr to nostr
Signed using Nostr key:
Tested on ionio: https://github.com/im-adithya/ionio/tree/alby-liquid
(change window.liquid to window.nostr in the Alby app (https://github.com/im-adithya/ionio/tree/alby-liquid/examples/alby-app) before testing)
> feat: add schnorr to nostr

- src/extension/background-script/actions/ln/__tests__/request.test.ts
Adds the test case where the user clicks on cancel in the prompt or removes the prompt by clicking on the close button.
- `chore`: Adds new test
Manually
> chore: add test for cancel

- src/app/screens/Receive/index.tsx
Changed back button functionality to go back to previous screen rather than home in receive screen.
Fixes #1542 
https://user-images.githubusercontent.com/74018438/218330325-13b58007-ecb3-41a9-8d72-e782b9d79e18.mp4
> fix: receive back button

- src/app/screens/LNURLPay/index.tsx
Added back button to send satoshis screen, while keeping in mind that we don't need a back button in prompt screen. I have used `navigate.isPrompt` for the same.
Fixes #1535 
https://user-images.githubusercontent.com/74018438/218791326-5481766c-103a-480d-a531-ae665b9bbfe7.mp4
> feat: back button in send sats screen (not prompt)

- src/i18n/i18nConfig.ts
> feat(i18n): support danish language

- src/common/lib/pubsub.ts
- src/extension/background-script/actions/ln/keysend.ts
- src/extension/background-script/actions/ln/sendPayment.ts
- src/extension/background-script/events/index.js
- src/extension/background-script/events/notifications.ts
This change starts calling ln.keysend.success for keysend payments (as desired), but that would mean we are not calling the success/failure notifications here: https://github.com/getAlby/lightning-browser-extension/blob/master/src/extension/background-script/events/index.js#L13-L14
Wanted to know if that's also done on purpose or I should add notifs for keysend payments
The `ln.keysend.success` event isn't being triggered at all because we only publish the `ln.sendPayment.success` event everytime.
Didn't test yet, require input.
> fix: add type in publishPaymentNotification

- src/app/components/SatButtons/index.tsx
- src/app/components/form/DualCurrencyField/index.tsx
- src/app/components/form/DualCurrencyField/range.tsx
- src/app/components/form/DualCurrencyField/rangeLabel.tsx
- src/app/screens/LNURLPay/index.tsx
- src/i18n/locales/en/translation.json
Have the LNURL payment form respect the provided `min` and `max` values. 
- Add the values to the form input 
- Disable SatsButtons that are out of the range
Fixes #1569 
[LNURLs used for testing](https://github.com/getAlby/lightning-browser-extension/wiki/%F0%9F%A4%A0-Alby-in-the-wild)
> feat: improve LNURL ux

- src/app/screens/Home/AllowanceView/index.tsx
- src/app/screens/Home/DefaultView/index.tsx
- src/app/screens/Transactions/index.tsx
- src/app/utils/payments.ts
- src/common/lib/api.ts
This is a follow up of the Transactions page https://github.com/getAlby/lightning-browser-extension/pull/2035. Same as on the transactions page, in DefaultView and AllowanceView `payments` are fetched and transformed to transactions. In the transactions feature this transformation is abstracted into the `convertPaymentsToTransactions` util function. This PR applies the `convertPaymentsToTransactions` abstraction for the two mentioned screens.
This by itself is actually a rather small refactor. However as we are dealing with `transactions` most of the time and the component consuming the data is also using the property `transactions`, I renamed a lot of properties from "payments" to "transactions" for consistency reasons. 
Fixes #2057
- `refactor`: Follow up of #2027 …
> refactor: use convertPaymentsToTransactions to convert payments

- src/extension/background-script/index.ts
- src/extension/background-script/state.ts
Uses `browser.storage.local` when `browser.storage.sync` is unavailable.
Fixes #
Tested in the latest Tor Browser
> fix(storage): use local when sync is unavailable

- src/app/screens/Unlock/index.tsx
> feat(Unlock): add container for max width on options screen

- src/app/components/form/Input/index.tsx
I have made the changes in the inputNode component className prop which had classNames function in which I added the extra condition to check whether the field is disabled or not and applied the styles as desired in the issue discription
Fixes #2292
The Public Key field can be now checked and it is according to the required UI which reflects that it is disabled in both light and dark modes. It can be seen in the above images.
> fix: style disabled state of inputs

- src/extension/content-script/batteries/Twitch.ts
- src/extension/content-script/batteries/index.ts
Search for ln address in channel bio.
Test channel: https://www.twitch.tv/rblb0/
> Add twitch support

- src/app/components/form/DualCurrencyField/index.tsx
Updated the current upper helper text in inputs is black in both light and dark theme to
Light theme: gray-700
Dark theme: neutral-400
Fixes #2291
> Fix :Correct upper helper text in inputs coloring #2291

- src/app/screens/Home/DefaultView/index.tsx
In order to have designs consistent for #2334 this PR reverses the order of DefaultView send/receive buttons
Fixes #2334
Manually
> feat: DefaultView reverse send/receive buttons order

- src/extension/background-script/index.ts
Possibly fixes #2305 :crossed_fingers: 
[MV3 Migration Guide](https://developer.chrome.com/docs/extensions/migrating/to-service-workers/#register-listeners)
> fix: register listeners sync

- src/app/components/Button/index.tsx
> fix: outline btn text color for dark mode

- src/app/context/AccountContext.tsx
Add balanceLoading to be used in #2318 BalanceBox. The current AccountContext "loading" is not viable, because the balance is loaded async.
Adds to #2236
> feat: add account-context balanceLoading

- src/app/screens/LNURLPay/index.tsx
- src/i18n/locales/en/translation.json
Toggle more fields on lnurlpay screen to have buttons visible.
Fixes #2370
Manually
> feat: lnurlpay screen toggle more fields

- src/extension/background-script/index.ts
(Merging into draft PR https://github.com/getAlby/lightning-browser-extension/pull/2364)
I believe the migrations should also run before the init() function finishes.
the migrate() function already checks whether it should run migrations, so I don't believe we only need to run it on update
> chore: also wait for migrations before finishing init

- src/app/screens/Discover/websites.json
Added https://musicsideproject.com/ and https://curiocaster.com/  to the "Discover" page under entertainment section. 
Fixes _ #2353 by @MoritzKa 
Current Discover Page -
Updated Discover Page- 
I have not yet uploaded the logos to the Content Delivery Network (CDN). Currently, I am using GitHub links. Could you please assist me with uploading them to the CDN as I am not familiar with the process?
> Added Music Side Project and CurioCaster  to the "Discover" page

- src/app/screens/Discover/websites.json
Add https://blowater.deno.dev/ to Nostr website page
> Update websites.json: add a Nostr client

- src/extension/background-script/connectors/lnc.ts
Removes the timeout for unloading the connector. 
Tested by switching accounts for multiple times without any problems.
> fix: remove timeout for lnc

- src/app/components/Badge/index.tsx
- src/app/components/PublishersTable/index.tsx
Removes excess padding in connected sites screen
--
- `chore`
> chore: minor UI improvements

- src/extension/content-script/batteries/StackOverflow.ts
Replace the htmltotext function with DomParser to avoid JS injections. 
`htmlTotext("abc<svg><svg onload=alert(1)</svg></svg>123")`
> fix: replace htmltotext function

- src/extension/background-script/connectors/lnc.ts
Allows you to switch accounts even if the LNC connection fails. Note: the connector is in a useless state here which should be fixed in [another PR](https://github.com/getAlby/lightning-browser-extension/issues/2468). 
Fixes _#2426_
Manually
> fix: unable to switch account if LNC connection fails

- src/app/components/CompanionDownloadInfo.tsx
- src/app/components/Hyperlink/index.tsx
- src/app/screens/ConfirmAddAccount/index.tsx
- src/common/utils/os.ts
- src/i18n/locales/en/translation.json
Adds an info box to the `addAccount` screen prompting users to install the companion app for TOR connectors. 
Waits on #2338 
TODO:
> feat: add companion download link in addAccount prompt

- src/app/components/Navbar/Navbar.tsx
Visibility on medium sizes was removed by this PR: https://github.com/getAlby/lightning-browser-extension/pull/2289 when the AccountMenu was using more space at the time. Now with the new design (without balance etc.) the nav can be shown again on medium screen sizes.
Also the spacing between the UserMenu and nav seems off.
Md before:
Md after:
Spacing before (discover too close to hamburger menu):
Spacing after:
> feat: show nav on md and improve spacing

- src/app/components/PublisherCard/index.tsx
Currently the Publisher card is only showing a tipping button (and the rest is hidden) when there is no image to display.
This happens because of a fixed height being set when there is no image.
I think this is some legacy code?
While visiting: https://github.com/getAlby/lightning-browser-extension
Before:
After:
> fix: remove fixed height when no image available

- package.json
- webpack.config.js
- yarn.lock
Removes `sass-loader` and dependencies since we don't use any SASS / SCSS features.
> fix: remove sass loader

- src/app/components/ConnectorForm/index.tsx
- src/app/router/Welcome/Welcome.tsx
- src/app/screens/Onboard/SetPassword/index.tsx
- tailwind.config.js
Optimize height of welcome screens so they fit for smaller screen sizes without moving the main button below the fold:
For larger screen sizes the elements on the page are centered vertically.
> fix: move primary buttons above fold for smaller screen sizes

- src/app/context/AccountContext.tsx
- src/app/screens/Options/TestConnection/index.tsx
fix the test connection screen which loads existing account details instead of showing newly added account details
Fixes #2550
Before:
After
> Bug Fix: testconnection showing details of existing account instead of newly added account

- src/common/settings.ts
i18next changed `resolvedLanguage` to be optional in a recent upgrade which causes a type error.
> fix: add default for locale

- src/extension/background-script/actions/lnurl/__tests__/auth.test.ts
- src/extension/background-script/actions/lnurl/auth.ts
LNURL auth did not match LUD-05 spec
- Manually, using same mnemonic as Phoenix wallet to login to https://lightsats.com
- Added unit tests
> fix: mnemonic auth to match LUD05 spec

- src/extension/background-script/connectors/alby.ts
Removes `signMessage` from list of supported methods for the Alby connector.
> fix: remove signMessage from alby connector

- .github/workflows/build.yml
- webpack.config.js
- Remove build variables from GH actions (not needed anymore as they are maintained in our webpack config)
- Added support for loading oAuth credentials from environment variables (for chrome & firefox simultaneously through running yarn package)
> fix: credential loading for different builds

- src/app/screens/Options/TestConnection/card.tsx
- src/app/screens/Options/TestConnection/index.tsx
The card component currently is only used for the test connection screen. Moved this component as it's not intended for general use anyway.
> fix: move card component

- src/app/styles/index.css
Currently some elements such as buttons have an explicit keyboard focus style with an orange ring.
Other things like links fallback to the default (blue) styling that the browser gives.
I think we should set a default here that matches with the explicit defined styles and overall brand (using the primary color).
Before:
After:
> feat: add default keyboard focus style

- src/app/components/PaymentSummary/index.tsx
- src/app/components/PublisherCard/index.tsx
Converge to the original designs.
> feat: publisher card ui

- src/app/screens/Receive/index.tsx
do not show copy lightning address button for lndhub accounts
Fixes #2618 
by checking on lndhub account
> fix: show copy lightning address button only for oauth users

- src/i18n/locales/en/translation.json
Rename "account information" to "account settings".
> fix: rename account settings heading

- src/app/router/Options/Options.tsx
On the options.html page `/` currently redirects you to the websites. 
Since we redirect users to `/` when switching accounts this takes you to the websites page. 
I think it would be better to take users to the wallet page as it's probably the most commonly used one.
> fix: make wallet page the startpage for the options view

- src/app/screens/Home/DefaultView/index.tsx
- src/app/screens/Home/index.tsx
When a user is on a page where there is an allowance, the publisher widget is rendered in two subsequent views: 
While the publisher widget makes sense on the home screen when there is NO allowance, I think it's duplicate when a user has already used the website before and should be hidden on the wallet page.
> fix: don't render the publisher widget if there is an allowance

- src/extension/background-script/actions/accounts/select.ts
- src/extension/content-script/onendnostr.js
- src/extension/content-script/onendwebln.js
- src/extension/providers/webln/index.ts
remove enable from emit function which causes unnecessary dialogue open post message only for webln enabled pages, so that malicious pages doesn't listen to such events this also results in emitting the event only when we are on webln enabled page
> fix: events improvements

- src/app/screens/connectors/ConnectGaloy/index.tsx
- src/app/screens/connectors/ConnectKollider/index.tsx
- src/extension/background-script/connectors/galoy.ts
- src/extension/background-script/connectors/kollider.ts
- src/extension/background-script/connectors/lndhub.ts
- src/extension/background-script/connectors/nativelndhub.ts
This header is a response header. Sending it from a client makes no sense. 
> The Access-Control-Allow-Origin header is included in the response from one website to a request originating from another website, and identifies the permitted origin of the request. A web browser compares the Access-Control-Allow-Origin with the requesting website's origin and permits access to the response if they match.
> fix: remove access-control-allow-origin

- src/app/screens/ConfirmPayment/index.tsx
- src/app/screens/Enable/index.tsx
- src/app/screens/LNURLAuth/index.tsx
- src/app/screens/LNURLChannel/index.tsx
- src/app/screens/MakeInvoice/index.tsx
- src/i18n/locales/en/translation.json
Removes warning from different prompts as you already connected with this site. The only place where this message would make sense is in the enable() screen. 
I found those messages do more harm than good and leave the user puzzled. What does it mean to "trust a website"?
> fix: remove "only connect with sites you trust"

- src/extension/providers/liquid/index.ts
Require clients to explicitly call enable() before any other method calls. (this is also how Marina wallet seems to do it right now)
> fix: add explicit enable call for window.liquid

- src/app/screens/Bitcoin/ConfirmGetAddress/index.tsx
- src/app/screens/Liquid/ConfirmGetAddress.tsx
- src/app/screens/Nostr/Confirm.tsx
- src/app/screens/Nostr/ConfirmGetPublicKey.tsx
Remember permissions by default for less critical operations to minimize popups seen during daily usage: 
- `webbtc.getAddress()`
- `liquid.getAddress()`
- `nostr.getPublicKey()`
- `nostr.nip04.encrypt()` and `nostr.nip04.decrypt()`
> feat: remember permissions by default

- src/app/components/Avatar/index.tsx
+ I have a legacy, non-square avatar that was uploaded before https://github.com/getAlby/getalby.com/commit/079710187ed4b09c405f23e6b35ec6a82a97759b:
https://uploads.getalby-assets.com/uploads/lightning_address/avatar/2893/thumb_jan-koegel_yours-truly.jpg
+ semi-tested, I only modified the CSS via my web inspector but did not rebuild the extension on my machine.
+ `.object-cover` is documented here: https://tailwindcss.com/docs/object-fit
> fix: support for non-square avatars

- src/manifest.json
set web accessible resources for firefox to avoid warning 
> fix: web accessible resources are not set properly for firefox

- src/extension/background-script/connectors/alby.ts
Prefer invoice comment over memo for Alby accounts.
> fix: use comment if available for alby invoices

- src/extension/content-script/liquid.js
- src/extension/content-script/nostr.js
- src/extension/content-script/webbtc.js
user makes a call. starts the onboarding process but doesn't setup the click. now the user makes the call again. in this case route will not be overridden because of account check. also i feel we don't need that
> feat: handle case when user goes to onboard but doesn't setup master key

- src/extension/background-script/actions/ln/__tests__/request.test.ts
- src/extension/background-script/actions/ln/request.ts
webln.request always fails because provided method does not match supported methods (prefixed with `request.`)
Manually, with webln sandbox (also needs a fix there)
> fix: webln request supported methods check

- src/extension/background-script/actions/accounts/select.ts
we query active tabs and iterate over them. if we have the tab that doesn't have the content script for such tab when we do postMessage. the error, receiving end does not exist will be thrown and we will get out of the function. this can lead to not notifying to active tabs
for eg. [tab not having content script, tab having content script]
tab having a content script is in the second place of the array. when we iterate and post message. we will get error for tab present in first position. and hence no notification logic will be executed  for tab which is on second position of the array.
solution would be. handle errors inside for loop instead of top level function
- For …
> feat: send message to all the valid tabs which has receiving end

- src/app/screens/Accounts/NostrSettings/index.tsx
show nsec format instead of hex for private key in nostr settings page
Manually
> fix: show nsec format in nostr settings page

- src/app/screens/Enable/WebbtcEnable.tsx
- src/i18n/locales/en/translation.json
use webbtc enable component in webbtc enable screen
Fixes  #2779 
> fix: use webbtc enable screen for webbtc provider

- src/app/components/QRCode/index.tsx
The QR code in the receive screen is not scannable when the lightning address name is <=3 characters. The issue might be due to the addition of avatar on the QR code. Few changes to fix this issue might be - increase the QR size, decrease the avatar size, Increase the error correction.
I increased the EC level as this seemed to be the best approach for it.
Fixes #2774 
These are few lightning addresses which can be used to test whether the QR is working after this change(hardcoded).
<p float="left">
</p>
Hardcoded the lightning address and checked whether it is working for lightning addresses with less than three characters.
> fix: made the QR code scannable for even shorter lightning addresses

- src/app/screens/Accounts/Detail/index.tsx
Added the validation for not allowing empty account names using the required attribute.
Fixes #2528 
tested manually by trying to save empty account name.
> fix: add validation to the account name input field 

- src/app/screens/ReceiveInvoice/index.tsx
Fix style issues #2816 - add justify-between for "receive another payment" button in "receive" screen.
Fixes #2816
Manually
> fix: receive another payment button styles

- src/i18n/i18nConfig.ts
- src/i18n/locales/de/translation.json
This PR enables "German" as a language in the extension. Translations seem more or less complete, however there are quite some really bad translations in there (e.g. connected sites <> Verbundene Standorte) :sweat: 
Would love to get some help from a native german speaking person on reviewing the translations on Weblate and making sure everything is properly translated: 
https://hosted.weblate.org/projects/getalby-lightning-browser-extension/getalby-lightning-browser-extension/de/
> feat: add de to supported locales

- src/extension/background-script/connectors/alby.ts
Cache `getInfo()` calls on connector level for the lifetime of the connector. (changing accounts will reload the info as every time a new instance is created)
> fix: caching getInfo calls

- src/app/components/TransactionsTable/TransactionModal.tsx
- Adds the title to the detail layout
- Some smaller layout fixes for overflowing text
> fix: add description to transaction modal, layout fixes

- package.json
- src/extension/background-script/connectors/alby.ts
- yarn.lock
Adds the preimage, depends on https://github.com/getAlby/js-sdk/pull/132
> feat: add preimage to transactions

- doc/SETUP.md
- doc/SETUP_ANDROID.md
initial version of setup guide to run and debug extension on firefox android
> feat: write setup guide for firefox for android

- src/app/components/Modal/index.tsx
- src/app/components/TransactionsTable/TransactionModal.tsx
Long transaction descriptions (such as in satograms) did make the modal unusable due to the overflow-hidden in the modal. 
Also made the first column in the TransactionDetailRow a bit smaller so the descriptions have more space.
> fix: add y overflow to the modal

- src/app/components/Modal/index.tsx
- src/app/components/TransactionsTable/TransactionModal.tsx
- src/app/components/TransactionsTable/index.tsx
- src/i18n/locales/en/translation.json
- Top align modal
- Spacing fixes
- Icon sizes
> fix: transaction list ui fixes

- src/app/components/toasts/ConnectionErrorToast.tsx
Fixing broken url in the error toast for new account creation 
Broken url:
https://guides.getalby.com/user-guide/alby-browser-extension/connect-lightning-wallets-and-nodes-to-alby-extension
New url:
https://guides.getalby.com/user-guide/v/alby-account-and-browser-extension/alby-browser-extension/connect-lightning-wallets-and-nodes-to-the-alby-extension
No extensive testing done - its just an url change
- [x ] Manual testing
> fix: broken url to documentation in error toast

- static/views/popup.html
- static/views/prompt.html
make the popup responsive. so that it fits perfectly on desktop and mobile screens
before: 
after: 
> feat: make popup view responsive

- src/extension/inpage-script/index.js
- src/extension/providers/alby/index.ts
allow 
window.alby.webln...
window.alby.nostr...
window.alby.webbtc...
window.alby.liquid...
> feat: use other providers under alby provider

- src/extension/background-script/connectors/alby.ts
- src/manifest.json
- webpack.config.js
one way we can eliminate identity api is to use completely native browser api so that we can support all the browsers including firefox for android
doesn't require any hacks or content script. just using tabs api and event listeners which works on all the browsers including android
> feat: handle auth flow natively

- src/extension/background-script/connectors/lnc.ts
- src/extension/background-script/connectors/lnd.ts
- src/i18n/locales/en/translation.json
this change whitelists some more webln.request() calls to manage onchain addresses.
testable on: 
https://liquimercado-lnd.getalby.repl.co/dashboard
> feat: add lnd wallet calls to get and list onchain addresses

- src/app/context/AccountContext.tsx
- src/app/router/Welcome/Welcome.tsx
security fix to not allow to bypass unlock screen and read unsensitive data
Fixes  #2915 
try to access welcome.html when the extension is unlocked and locked. 
> fix: don't allow to bypass unlock screen and access welcome screen

- src/app/components/Container.tsx
- src/app/components/Modal/index.tsx
- src/app/router/Popup/Popup.tsx
- src/app/router/Prompt/Prompt.tsx
- src/app/screens/LNURLPay/index.tsx
- static/views/popup.html
- static/views/prompt.html
fix normal popups and popups which has additonal expandible fields such as lnurlpay popup
> feat: max popup screens fit

- src/extension/background-script/connectors/galoy.ts
Changes the galoy connector to return the preimage when the payment settles over lightning.
Intraledger settlements are not yet returning a preimage until https://github.com/GaloyMoney/galoy/issues/3735 is solved.
discussed in: #2946
manually loading to Firefox
> fix: return preimage for ln settlement in galoy connector

- src/app/components/Modal/index.tsx
- src/app/components/TransactionsTable/TransactionModal.tsx
no scrollbar in the transaction modal popup
> feat: no scrollbar in transaction modal popup

- src/extension/background-script/connectors/commando.ts
https://cdecker-lightning.readthedocs.io/lightning-keysend.7.html#randomization
cln uses ```amount_msat``` and ```amount_sent_msat``` values and no more returns ```msatoshi ```value. we currently pass the wrong values in the total amount and fees to the extension which don't exist in response. resulting into ```NaN sats``` output for outgoing db transactions
> fix: return correct value for amount and fees for cln send payment

- src/extension/background-script/connectors/commando.ts
https://cdecker-lightning.readthedocs.io/lightning-listinvoices.7.html#return-value
amount_msat is optional and may not be included in the payments like keysends. as we filter and show only paid transactions ```amount_received_msat``` is always present. 
if there is no key value pair for amount in transactions. it shows either 0 or NaN 
tried multiple types payments i see keysends don't contains amount_msat field
checked outgoingpayment parameters. transaction list shall be fine by now
Fixes  #2910 
> fix: getInvoices method for cln (NaN amount)

- src/extension/background-script/actions/accounts/add.ts
- src/extension/background-script/actions/accounts/unlock.ts
- src/extension/background-script/actions/mnemonic/generateMnemonic.ts
auto masterkey generation during account creation
Fixes  #2921
create account. go to account settings see keys generated already
> feat: default masterkey generation

- src/app/components/LocaleSwitcher/LocaleSwitcher.tsx
- src/app/router/Welcome/Welcome.tsx
- src/app/screens/Settings/index.tsx
local switcher in onboardings screen
custom design to use it diffferent places 
Fixes  #2918
> feat: custom locale switcher

- src/app/components/PaymentSummary/index.tsx
avoid overflow for continuous strings
Fixes #3009 
single continuous string:
non continuous strings:
noncontinuous strings having some larger continuous strings:
> feat: avoid overflow for continuous strings in description

- src/app/components/mnemonic/MnemonicInputs/index.tsx
Pops the words after 12, so that we can restrict the mnemonic inputs to 12 max.
Fixes #3038
https://github.com/getAlby/lightning-browser-extension/assets/64399555/0df0c252-f706-4493-a083-4b42d9a68be8
> fix(mnemonic): restrict input fields to 12

- src/app/screens/LNURLChannel/index.tsx
show error in popup while having error for claming lnurl channel
> feat: proper error handling

- src/app/components/AccountMenu/index.tsx
- src/app/components/Menu/MenuItemButton.tsx
> fix: menu-layout

- src/app/screens/LNURLWithdraw/index.test.tsx
- src/app/screens/LNURLWithdraw/index.tsx
proper error handling for lnurl withdraw
> fix: proper error handling for lnurl withdraw

- package.json
- yarn.lock
This fixes error messages not being displayed from errors in the NWC connector due to Alby JS SDK previously not throwing proper error objects (therefore the `message` field being undefined and the error falling back to "Something went wrong")
> chore: bump Alby JS SDK to 3.4.0

- src/common/lib/lnurl.ts
throw actual error reasons and messages to send and receive screen while performing lnurl actions
try lnurl withdraw
> fix: throw actual error reason and messages to screen

- src/app/components/UserMenu/index.tsx
shrink-0 usermenu icons
Fixes  #3111 
> fix: shrink-0 user menu icons

- src/i18n/i18nConfig.ts
add persian language locale switcher
> feat: add fa locale

- src/app/screens/Accounts/Detail/index.tsx
show lnaddress settings only to alby auth account
> fix: show lnaddress settings only to alby oauth accounts

- src/app/components/ContentMessage/index.tsx
fix contentMessage component for longer descriptions
make sure buttons always visible in viewport
before: 
after:
> feat: handle longer descriptions + buttons always visible in viewport

- src/app/screens/Accounts/Detail/index.tsx
show lnaddress only when oauth account settings are accessed
> feat: show lnaddress only when oauth  account settings are accessed

- src/app/components/Button/index.tsx
- src/app/components/ConnectorPath/index.tsx
fix primary button text overflow happens usually when loading state comes in and button has long text
> fix: primary button overflow

- static/views/popup.html
fix scrollbar and shift of view in popup for latest chromium browsers
before: 
now:
> fix: scrollbar on extension popup

- package.json
- tailwind.config.js
- yarn.lock
The menu's (such as UserMenu / AccountMenu) now feel "laggy" as there is no animation on the scaling. It jumps weirdly. I found out that tailwindcss-3d adjusts many classes and breaks the "scaling" transitions.
fix: remove the tailwindcss-3d plugin and create a custom plugin that provides the class that was actually used from the plugin: translate-z-0.
> fix: tailwindcss-3d plugin breaks scale animations

- src/extension/background-script/connectors/nwc.ts
currently if we paste node id in send screen. the custom_records will be undefined. and keysend thrws error while converting it to tlv records. keysend shall be successfully even if custom_records are undefined
go to send -> paste node id -> keysend will be successfull
> fix: nwc keysend method and custom record conversion when custom records is not passed

- src/app/screens/Send/index.tsx
Fixes #3227 
before:
if its not lnurl then we check for lnaddress. but sometimes lnaddress containing "lnurl" in it makes isLnurl = true leading to potential errors 
after: 
we check for both lnaddress and lnurl separately.
> fix: lnaddress containing lnurl prefixes

- src/extension/background-script/connectors/alby.ts
add identifier to the auth url. 
persist in account config
next time the refresh token expires, and user is logged in into different account on getalby.com we avoid weird behaviour and ask user to login again (potentially the correct account)
> feat: add identifier in auth url

- src/app/context/AccountContext.tsx
- src/app/screens/Home/DefaultView/index.tsx
- src/common/lib/api.ts
- src/i18n/locales/en/translation.json
- src/types.ts
shall be merged after https://github.com/getAlby/getalby.com/pull/1847 is deployed
> feat: \using fee credits

- src/extension/content-script/batteries/Medium.ts
- src/extension/content-script/batteries/Reddit.ts
fix reddit battery
fix medium battery works for medium posts, author pages, post pages
> fix: reddit +medium battery

- doc/SETUP.md
remove e2e test instructions from setup guide
> fix: remove e2e test instructions from setup docs

- src/app/screens/Onboard/PinExtension/index.tsx
Aligned all onboarding cards to `max-w-xl` (576px) for better consistency across different screen sizes.
Fixes #2615 
- Manually tested the onboarding cards on different screen sizes to ensure they align correctly.
- Verified that the alignment works in both light and dark modes.
- Checked responsiveness to confirm no UI breakage.
> fix: align onboarding cards to max-w-xl (576px) #2615

- src/app/components/Toast/index.tsx
- Improved the toast UI to gracefully handle long error messages.
- Ensured error messages break properly on small screens.
- Added a dismiss button for long toasts or toasts with extended durations.
Fixes #3334
- Manually triggered error toasts with long LNURL error messages.
- Verified layout on mobile and desktop.
- Confirmed dismiss button shows conditionally and works.
> fix(toast): allow toast to handle long error messages and improve its responsiveness

- src/app/components/UserMenu/index.tsx
Added "Wallet Settings" option to the main menu to improve accessibility while maintaining the existing access point in the account menu. Many users were struggling to find the wallet settings which were only accessible through a small icon in the account menu. This change makes the feature more discoverable by placing it where users naturally look for it.
Fixes  #3300
I've manually tested the changes by:
1. Verifying the "Wallet Settings" option appears in the main menu
2. Confirming it correctly navigates to the account settings page when clicked
3. Ensuring the existing wallet settings icon in the account menu still works
4. Testing with different account types to ensure proper functionality
-  For UI-related changes
> feat: add Wallet Settings to main menu for improved accessibility

- package.json
- src/app/components/TransactionsTable/TransactionModal.tsx
- src/app/components/TransactionsTable/index.tsx
- src/app/screens/SendToBitcoinAddress/index.tsx
- src/app/screens/connectors/ConnectAlby/index.tsx
- src/app/utils/index.ts
- src/common/lib/api.ts
- src/extension/background-script/connectors/alby.ts
- src/extension/background-script/connectors/connector.interface.ts
- src/extension/background-script/connectors/nwc.ts
- src/types.ts
- yarn.lock
Updates `@getalby/sdk` to v6.0.0 to avoid importing types from dist folder
- `chore`
Tested by checking both Alby account and NWC connector (rest all are type imports which work well)
> chore: update @getalby/js-sdk to 6.0.0
